// Generated by scripts/extract-resource-links.mjs from
// IBG_Target_Cities_Resource_Links_1.xlsx — do not hand-edit; re-run the
// script if the source sheet changes.

export interface CityResourceLinks {
  chamberUrl: string | null;
  citySiteUrl: string | null;
  stateCommerceUrl: string | null;
}

export interface SbaLink {
  label: string;
  url: string;
}

export const SBA_LINKS: SbaLink[] = [
  {
    "label": "Plan Your Business",
    "url": "https://www.sba.gov/business-guide/plan-your-business"
  },
  {
    "label": "Launch Your Business",
    "url": "https://www.sba.gov/business-guide/launch-your-business"
  },
  {
    "label": "Manage Your Business",
    "url": "https://www.sba.gov/business-guide/manage-your-business"
  },
  {
    "label": "Grow Your Business",
    "url": "https://www.sba.gov/business-guide/grow-your-business"
  }
];

export const CITY_RESOURCE_LINKS: Record<string, CityResourceLinks> = {
  "birmingham-al": {
    "chamberUrl": "https://www.birminghambusinessalliance.com/",
    "citySiteUrl": "https://www.birminghamal.gov/",
    "stateCommerceUrl": "https://www.madeinalabama.com/"
  },
  "huntsville-al": {
    "chamberUrl": "https://hsvchamber.org/",
    "citySiteUrl": "https://www.huntsvilleal.gov/",
    "stateCommerceUrl": "https://www.madeinalabama.com/"
  },
  "mobile-al": {
    "chamberUrl": "https://mobilechamber.com/",
    "citySiteUrl": "https://www.cityofmobile.gov/",
    "stateCommerceUrl": "https://www.madeinalabama.com/"
  },
  "montgomery-al": {
    "chamberUrl": "https://www.montgomerychamber.com/",
    "citySiteUrl": "https://www.montgomeryal.gov/",
    "stateCommerceUrl": "https://www.madeinalabama.com/"
  },
  "tuscaloosa-al": {
    "chamberUrl": "https://www.tuscaloosachamber.com/",
    "citySiteUrl": "https://www.tuscaloosa.com/",
    "stateCommerceUrl": "https://www.madeinalabama.com/"
  },
  "anchorage-ak": {
    "chamberUrl": "https://www.anchoragechamber.org/",
    "citySiteUrl": "https://www.muni.org/",
    "stateCommerceUrl": "https://www.commerce.alaska.gov/"
  },
  "buckeye-az": {
    "chamberUrl": "https://buckeyevalleychamber.org/",
    "citySiteUrl": "https://www.buckeyeaz.gov/",
    "stateCommerceUrl": "https://www.azcommerce.com/"
  },
  "chandler-az": {
    "chamberUrl": "https://www.chandlerchamber.com/",
    "citySiteUrl": "https://www.chandleraz.gov/",
    "stateCommerceUrl": "https://www.azcommerce.com/"
  },
  "gilbert-az": {
    "chamberUrl": "https://www.gilbertaz.com/",
    "citySiteUrl": "https://www.gilbertaz.gov/",
    "stateCommerceUrl": "https://www.azcommerce.com/"
  },
  "glendale-az": {
    "chamberUrl": "https://www.glendaleazchamber.org/",
    "citySiteUrl": "https://www.glendaleaz.com/",
    "stateCommerceUrl": "https://www.azcommerce.com/"
  },
  "goodyear-az": {
    "chamberUrl": "https://southwestvalleychamber.org/",
    "citySiteUrl": "https://www.goodyearaz.gov/",
    "stateCommerceUrl": "https://www.azcommerce.com/"
  },
  "mesa-az": {
    "chamberUrl": "https://www.mesachamber.org/",
    "citySiteUrl": "https://www.mesaaz.gov/",
    "stateCommerceUrl": "https://www.azcommerce.com/"
  },
  "peoria-az": {
    "chamberUrl": "https://peoriachamber.com/",
    "citySiteUrl": "https://www.peoriaaz.gov/",
    "stateCommerceUrl": "https://www.azcommerce.com/"
  },
  "phoenix-az": {
    "chamberUrl": "https://www.phoenixchamber.com/",
    "citySiteUrl": "https://www.phoenix.gov/",
    "stateCommerceUrl": "https://www.azcommerce.com/"
  },
  "scottsdale-az": {
    "chamberUrl": "https://www.scottsdalechamber.com/",
    "citySiteUrl": "https://www.scottsdaleaz.gov/",
    "stateCommerceUrl": "https://www.azcommerce.com/"
  },
  "surprise-az": {
    "chamberUrl": "https://surpriseregionalchamber.com/",
    "citySiteUrl": "https://www.surpriseaz.gov/",
    "stateCommerceUrl": "https://www.azcommerce.com/"
  },
  "tempe-az": {
    "chamberUrl": "https://www.tempechamber.org/",
    "citySiteUrl": "https://www.tempe.gov/",
    "stateCommerceUrl": "https://www.azcommerce.com/"
  },
  "tucson-az": {
    "chamberUrl": "https://www.chamberofsouthernarizona.com/",
    "citySiteUrl": "https://www.tucsonaz.gov/",
    "stateCommerceUrl": "https://www.azcommerce.com/"
  },
  "little-rock-ar": {
    "chamberUrl": "https://www.littlerockchamber.com/",
    "citySiteUrl": "https://www.littlerock.gov/",
    "stateCommerceUrl": "https://www.commerce.arkansas.gov/"
  },
  "anaheim-ca": {
    "chamberUrl": "https://www.anaheimchamber.org/",
    "citySiteUrl": "https://www.anaheim.net/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "antioch-ca": {
    "chamberUrl": "https://www.antiochchamber.com/",
    "citySiteUrl": "https://www.antiochca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "apple-valley-ca": {
    "chamberUrl": "https://www.avchamber.org/",
    "citySiteUrl": "https://www.applevalley.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "bakersfield-ca": {
    "chamberUrl": "https://www.bakersfieldchamber.org/",
    "citySiteUrl": "https://www.bakersfieldcity.us/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "berkeley-ca": {
    "chamberUrl": "https://www.berkeleychamber.com/",
    "citySiteUrl": "https://berkeleyca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "carlsbad-ca": {
    "chamberUrl": "https://carlsbad.org/",
    "citySiteUrl": "https://www.carlsbadca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "chico-ca": {
    "chamberUrl": "https://chicochamber.com/",
    "citySiteUrl": "https://chico.ca.us/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "chino-ca": {
    "chamberUrl": "https://www.chinovalleychamber.com/",
    "citySiteUrl": "https://www.chinohills.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "chula-vista-ca": {
    "chamberUrl": "https://www.chulavistachamber.org/",
    "citySiteUrl": "https://www.chulavistaca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "concord-ca": {
    "chamberUrl": "https://www.concordchamber.com/",
    "citySiteUrl": "https://www.cityofconcord.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "corona-ca": {
    "chamberUrl": "https://www.mycoronachamber.org/",
    "citySiteUrl": "https://www.coronaca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "costa-mesa-ca": {
    "chamberUrl": "https://www.costamesachamber.com/",
    "citySiteUrl": "https://www.costamesaca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "daly-city-ca": {
    "chamberUrl": "https://www.dalycity-colmachamber.org/",
    "citySiteUrl": "https://www.dalycity.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "downey-ca": {
    "chamberUrl": "https://www.downeychamber.com/",
    "citySiteUrl": "https://www.downeyca.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "el-cajon-ca": {
    "chamberUrl": "https://www.eastcountychamber.org/",
    "citySiteUrl": "https://www.elcajon.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "el-monte-ca": {
    "chamberUrl": "https://www.elmontechamber.org/",
    "citySiteUrl": "https://www.elmonteca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "elk-grove-ca": {
    "chamberUrl": "https://www.elkgrovechamber.com/",
    "citySiteUrl": "https://www.elkgrovecity.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "escondido-ca": {
    "chamberUrl": "https://escondidochamber.org/",
    "citySiteUrl": "https://www.escondido.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "fontana-ca": {
    "chamberUrl": "https://www.fontanachamber.com/",
    "citySiteUrl": "https://www.fontanaca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "fremont-ca": {
    "chamberUrl": "https://www.fremontbusiness.com/",
    "citySiteUrl": "https://www.fremont.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "fresno-ca": {
    "chamberUrl": "https://www.fresnochamber.com/",
    "citySiteUrl": "https://www.fresno.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "fullerton-ca": {
    "chamberUrl": "https://www.fullertonchamber.com/",
    "citySiteUrl": "https://www.cityoffullerton.com/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "glendale-ca": {
    "chamberUrl": "https://www.glendalechamber.com/",
    "citySiteUrl": "https://www.glendaleca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "hayward-ca": {
    "chamberUrl": "https://www.hayward.org/",
    "citySiteUrl": "https://www.hayward-ca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "hemet-ca": {
    "chamberUrl": "https://www.hemetsanjacintochamber.com/",
    "citySiteUrl": "https://www.hemetca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "hesperia-ca": {
    "chamberUrl": "https://www.hesperiachamber.org/",
    "citySiteUrl": "https://www.cityofhesperia.us/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "huntington-beach-ca": {
    "chamberUrl": "https://www.hbchamber.org/",
    "citySiteUrl": "https://www.huntingtonbeachca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "inglewood-ca": {
    "chamberUrl": "https://www.inglewoodchamber.net/",
    "citySiteUrl": "https://www.cityofinglewood.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "irvine-ca": {
    "chamberUrl": "https://www.irvinechamber.com/",
    "citySiteUrl": "https://www.cityofirvine.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "jurupa-valley-ca": {
    "chamberUrl": "https://www.jvchamber.org/",
    "citySiteUrl": "https://www.jurupavalley.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "la-mesa-ca": {
    "chamberUrl": "https://www.lamesachamber.com/",
    "citySiteUrl": "https://www.cityoflamesa.us/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "long-beach-ca": {
    "chamberUrl": "https://www.lbchamber.com/",
    "citySiteUrl": "https://www.longbeach.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "los-angeles-ca": {
    "chamberUrl": "https://www.lachamber.com/",
    "citySiteUrl": "https://www.lacity.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "menifee-ca": {
    "chamberUrl": "https://menifeevalleychamber.com/",
    "citySiteUrl": "https://www.cityofmenifee.us/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "mission-viejo-ca": {
    "chamberUrl": "https://www.missionviejochamber.org/",
    "citySiteUrl": "https://cityofmissionviejo.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "modesto-ca": {
    "chamberUrl": "https://www.modchamber.org/",
    "citySiteUrl": "https://www.modestogov.com/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "moreno-valley-ca": {
    "chamberUrl": "https://www.mvchamber.org/",
    "citySiteUrl": "https://www.moval.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "murrieta-ca": {
    "chamberUrl": "https://www.murrietachamber.org/",
    "citySiteUrl": "https://www.murrietaca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "oakland-ca": {
    "chamberUrl": "https://www.oaklandchamber.com/",
    "citySiteUrl": "https://www.oaklandca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "oceanside-ca": {
    "chamberUrl": "https://www.oceansidechamber.com/",
    "citySiteUrl": "https://www.oceansideca.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "ontario-ca": {
    "chamberUrl": "https://www.ontario.org/",
    "citySiteUrl": "https://www.ontarioca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "palmdale-ca": {
    "chamberUrl": "https://www.palmdalechamber.org/",
    "citySiteUrl": "https://www.cityofpalmdale.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "pasadena-ca": {
    "chamberUrl": "https://www.pasadena-chamber.org/",
    "citySiteUrl": "https://www.cityofpasadena.net/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "pomona-ca": {
    "chamberUrl": "https://www.pomonachamber.org/",
    "citySiteUrl": "https://www.pomonaca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "redding-ca": {
    "chamberUrl": "https://www.reddingchamber.com/",
    "citySiteUrl": "https://www.cityofredding.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "redwood-city-ca": {
    "chamberUrl": "https://www.redwoodcitychamber.com/",
    "citySiteUrl": "https://www.redwoodcity.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "rialto-ca": {
    "chamberUrl": "https://www.rialtochamber.org/",
    "citySiteUrl": "https://www.yourrialto.com/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "riverside-ca": {
    "chamberUrl": "https://www.riverside-chamber.com/",
    "citySiteUrl": "https://www.riversideca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "roseville-ca": {
    "chamberUrl": "https://www.rosevillechamber.com/",
    "citySiteUrl": "https://www.roseville.ca.us/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "sacramento-ca": {
    "chamberUrl": "https://metrochamber.org/",
    "citySiteUrl": "https://www.cityofsacramento.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "salinas-ca": {
    "chamberUrl": "https://www.salinaschamber.com/",
    "citySiteUrl": "https://www.cityofsalinas.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "san-bernardino-ca": {
    "chamberUrl": "https://www.sbchamber.org/",
    "citySiteUrl": "https://www.sbcity.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "san-diego-ca": {
    "chamberUrl": "https://www.sdchamber.org/",
    "citySiteUrl": "https://www.sandiego.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "san-francisco-ca": {
    "chamberUrl": "https://www.sfchamber.com/",
    "citySiteUrl": "https://www.sf.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "san-jose-ca": {
    "chamberUrl": "https://www.sjchamber.com/",
    "citySiteUrl": "https://www.sanjoseca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "san-leandro-ca": {
    "chamberUrl": "https://www.sanleandrochamber.com/",
    "citySiteUrl": "https://www.sanleandro.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "san-marcos-ca": {
    "chamberUrl": "https://www.sanmarcoschamber.com/",
    "citySiteUrl": "https://www.san-marcos.net/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "san-ramon-ca": {
    "chamberUrl": "https://www.sanramon.org/",
    "citySiteUrl": "https://www.sanramon.ca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "santa-ana-ca": {
    "chamberUrl": "https://www.santaanachamber.com/",
    "citySiteUrl": "https://www.santa-ana.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "santa-barbara-ca": {
    "chamberUrl": "https://sbscchamber.com/",
    "citySiteUrl": "https://www.santabarbaraca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "santa-clara-ca": {
    "chamberUrl": "https://www.santaclarachamber.org/",
    "citySiteUrl": "https://www.santaclaraca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "santa-clarita-ca": {
    "chamberUrl": "https://www.scvchamber.com/",
    "citySiteUrl": "https://www.santaclarita.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "santa-maria-ca": {
    "chamberUrl": "https://www.santamaria.com/",
    "citySiteUrl": "https://www.cityofsantamaria.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "santa-rosa-ca": {
    "chamberUrl": "https://www.santarosachamber.com/",
    "citySiteUrl": "https://www.srcity.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "simi-valley-ca": {
    "chamberUrl": "https://www.simichamber.org/",
    "citySiteUrl": "https://www.simivalley.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "stockton-ca": {
    "chamberUrl": "https://www.stocktonchamber.org/",
    "citySiteUrl": "https://www.stocktonca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "sunnyvale-ca": {
    "chamberUrl": "https://www.svcoc.org/",
    "citySiteUrl": "https://www.sunnyvale.ca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "temecula-ca": {
    "chamberUrl": "https://www.temecula.org/",
    "citySiteUrl": "https://www.temeculaca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "thousand-oaks-ca": {
    "chamberUrl": "https://www.towlvchamber.org/",
    "citySiteUrl": "https://www.toaks.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "torrance-ca": {
    "chamberUrl": "https://www.torrancechamber.com/",
    "citySiteUrl": "https://www.torranceca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "upland-ca": {
    "chamberUrl": "https://www.uplandchamber.org/",
    "citySiteUrl": "https://www.uplandca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "vacaville-ca": {
    "chamberUrl": "https://www.vacavillechamber.com/",
    "citySiteUrl": "https://www.cityofvacaville.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "vallejo-ca": {
    "chamberUrl": "https://www.vallejochamber.com/",
    "citySiteUrl": "https://www.cityofvallejo.net/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "ventura-ca": {
    "chamberUrl": "https://www.venturachamber.com/",
    "citySiteUrl": "https://www.cityofventura.ca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "victorville-ca": {
    "chamberUrl": "https://www.vvchamber.com/",
    "citySiteUrl": "https://www.victorvilleca.gov/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "visalia-ca": {
    "chamberUrl": "https://www.visaliachamber.org/",
    "citySiteUrl": "https://www.visalia.city/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "vista-ca": {
    "chamberUrl": "https://www.vistachamber.org/",
    "citySiteUrl": "https://www.cityofvista.com/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "west-covina-ca": {
    "chamberUrl": "https://www.westcovinachamber.com/",
    "citySiteUrl": "https://www.westcovina.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  },
  "arvada-co": {
    "chamberUrl": "https://www.arvadachamber.org/",
    "citySiteUrl": "https://www.arvadaco.gov/",
    "stateCommerceUrl": "https://choosecolorado.com/"
  },
  "aurora-co": {
    "chamberUrl": "https://www.aurorachamber.org/",
    "citySiteUrl": "https://www.auroragov.org/",
    "stateCommerceUrl": "https://choosecolorado.com/"
  },
  "boulder-co": {
    "chamberUrl": "https://boulderchamber.com/",
    "citySiteUrl": "https://bouldercolorado.gov/",
    "stateCommerceUrl": "https://choosecolorado.com/"
  },
  "centennial-co": {
    "chamberUrl": "https://www.southmetrochamber.com/",
    "citySiteUrl": "https://www.centennialco.gov/",
    "stateCommerceUrl": "https://choosecolorado.com/"
  },
  "colorado-springs-co": {
    "chamberUrl": "https://coloradospringschamberedc.com/",
    "citySiteUrl": "https://coloradosprings.gov/",
    "stateCommerceUrl": "https://choosecolorado.com/"
  },
  "denver-co": {
    "chamberUrl": "https://denverchamber.org/",
    "citySiteUrl": "https://www.denvergov.org/",
    "stateCommerceUrl": "https://choosecolorado.com/"
  },
  "fort-collins-co": {
    "chamberUrl": "https://www.fcchamber.org/",
    "citySiteUrl": "https://www.fcgov.com/",
    "stateCommerceUrl": "https://choosecolorado.com/"
  },
  "lakewood-co": {
    "chamberUrl": "https://www.lakewoodchamber.org/",
    "citySiteUrl": "https://www.lakewood.org/",
    "stateCommerceUrl": "https://choosecolorado.com/"
  },
  "longmont-co": {
    "chamberUrl": "https://longmontchamber.org/",
    "citySiteUrl": "https://www.longmontcolorado.gov/",
    "stateCommerceUrl": "https://choosecolorado.com/"
  },
  "pueblo-co": {
    "chamberUrl": "https://www.pueblochamber.org/",
    "citySiteUrl": "https://www.pueblo.us/",
    "stateCommerceUrl": "https://choosecolorado.com/"
  },
  "thornton-co": {
    "chamberUrl": "https://www.metronorthchamber.com/",
    "citySiteUrl": "https://www.thorntonco.gov/",
    "stateCommerceUrl": "https://choosecolorado.com/"
  },
  "westminster-co": {
    "chamberUrl": "https://www.metronorthchamber.com/",
    "citySiteUrl": "https://www.westminsterco.gov/",
    "stateCommerceUrl": "https://choosecolorado.com/"
  },
  "bridgeport-ct": {
    "chamberUrl": "https://www.bridgeportchamber.com/",
    "citySiteUrl": "https://www.bridgeportct.gov/",
    "stateCommerceUrl": "https://portal.ct.gov/DECD"
  },
  "hartford-ct": {
    "chamberUrl": "https://www.metrohartford.com/",
    "citySiteUrl": "https://www.hartfordct.gov/",
    "stateCommerceUrl": "https://portal.ct.gov/DECD"
  },
  "new-haven-ct": {
    "chamberUrl": "https://www.gnhcc.com/",
    "citySiteUrl": "https://www.newhavenct.gov/",
    "stateCommerceUrl": "https://portal.ct.gov/DECD"
  },
  "stamford-ct": {
    "chamberUrl": "https://www.stamfordchamber.com/",
    "citySiteUrl": "https://www.stamfordct.gov/",
    "stateCommerceUrl": "https://portal.ct.gov/DECD"
  },
  "waterbury-ct": {
    "chamberUrl": "https://www.waterburychamber.com/",
    "citySiteUrl": "https://www.waterburyct.org/",
    "stateCommerceUrl": "https://portal.ct.gov/DECD"
  },
  "washington-dc": {
    "chamberUrl": "https://www.dcchamber.org/",
    "citySiteUrl": "https://dc.gov/",
    "stateCommerceUrl": "https://does.dc.gov/"
  },
  "altamonte-springs-fl": {
    "chamberUrl": "https://www.seminolebusiness.org/",
    "citySiteUrl": "https://www.altamonte.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "apollo-beach-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://hcfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "apopka-fl": {
    "chamberUrl": "https://www.apopkachamber.org/",
    "citySiteUrl": "https://www.apopka.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "azalea-park-fl": {
    "chamberUrl": "https://www.orlando.org/",
    "citySiteUrl": "https://www.orangecountyfl.net/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "bay-lake-fl": {
    "chamberUrl": "https://www.orlando.org/",
    "citySiteUrl": "https://www.orangecountyfl.net/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "belleair-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://www.townofbelleair.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "belleair-beach-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://www.cityofbelleairbeach.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "belleair-bluffs-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://belleairbluffs.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "boca-raton-fl": {
    "chamberUrl": "https://www.bocaratonchamber.com/",
    "citySiteUrl": "https://www.myboca.us/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "boynton-beach-fl": {
    "chamberUrl": "https://www.boyntonbeach.org/",
    "citySiteUrl": "https://www.boynton-beach.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "brandon-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://hcfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "brooksville-fl": {
    "chamberUrl": "https://www.hernandochamber.com/",
    "citySiteUrl": "https://www.cityofbrooksville.us/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "cape-coral-fl": {
    "chamberUrl": "https://www.capecoralchamber.com/",
    "citySiteUrl": "https://www.capecoral.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "carrollwood-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://hcfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "casselberry-fl": {
    "chamberUrl": "https://www.seminolebusiness.org/",
    "citySiteUrl": "https://www.casselberry.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "celebration-fl": {
    "chamberUrl": "https://www.kissimmeechamber.com/",
    "citySiteUrl": "https://www.osceola.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "chuluota-fl": {
    "chamberUrl": "https://www.seminolebusiness.org/",
    "citySiteUrl": "https://www.seminolecountyfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "clearwater-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://www.myclearwater.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "clermont-fl": {
    "chamberUrl": "https://www.southlakechamber-fl.com/",
    "citySiteUrl": "https://www.clermontfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "coral-springs-fl": {
    "chamberUrl": "https://www.csrchamber.com/",
    "citySiteUrl": "https://www.coralsprings.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "dade-city-fl": {
    "chamberUrl": "https://www.pascochamber.com/",
    "citySiteUrl": "https://www.dadecityfl.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "davie-fl": {
    "chamberUrl": "https://www.davie-coopercity.org/",
    "citySiteUrl": "https://www.davie-fl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "delray-beach-fl": {
    "chamberUrl": "https://www.delraybeach.com/",
    "citySiteUrl": "https://www.delraybeachfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "deltona-fl": {
    "chamberUrl": "https://www.deltona.org/",
    "citySiteUrl": "https://www.deltonafl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "disney-springs-fl": {
    "chamberUrl": "https://www.orlando.org/",
    "citySiteUrl": "https://www.orangecountyfl.net/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "doctor-phillips-fl": {
    "chamberUrl": "https://www.orlando.org/",
    "citySiteUrl": "https://www.orangecountyfl.net/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "dunedin-fl": {
    "chamberUrl": "https://www.dunedinfl.com/",
    "citySiteUrl": "https://www.dunedingov.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "eustis-fl": {
    "chamberUrl": "https://www.eustischamber.org/",
    "citySiteUrl": "https://www.eustis.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "fishhawk-ranch-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://hcfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "fort-lauderdale-fl": {
    "chamberUrl": "https://www.ftlchamber.com/",
    "citySiteUrl": "https://www.fortlauderdale.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "gainesville-fl": {
    "chamberUrl": "https://www.gainesvillechamber.com/",
    "citySiteUrl": "https://www.cityofgainesville.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "geneva-fl": {
    "chamberUrl": "https://www.seminolebusiness.org/",
    "citySiteUrl": "https://www.seminolecountyfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "gibsonton-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://hcfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "gulfport-fl": {
    "chamberUrl": "https://www.gulfport.us/",
    "citySiteUrl": "https://www.mygulfport.us/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "heathrow-fl": {
    "chamberUrl": "https://www.seminolebusiness.org/",
    "citySiteUrl": "https://www.seminolecountyfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "hialeah-fl": {
    "chamberUrl": "https://www.hialeahchamber.org/",
    "citySiteUrl": "https://www.hialeahfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "holiday-fl": {
    "chamberUrl": "https://www.pascochamber.com/",
    "citySiteUrl": "https://www.pascocountyfl.net/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "hollywood-fl": {
    "chamberUrl": "https://www.hollywoodchamber.org/",
    "citySiteUrl": "https://www.hollywoodfl.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "homestead-fl": {
    "chamberUrl": "https://www.southdadechamber.org/",
    "citySiteUrl": "https://www.cityofhomestead.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "horizon-west-fl": {
    "chamberUrl": "https://www.orlando.org/",
    "citySiteUrl": "https://www.orangecountyfl.net/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "hudson-fl": {
    "chamberUrl": "https://www.pascochamber.com/",
    "citySiteUrl": "https://www.pascocountyfl.net/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "indian-rocks-beach-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://www.indian-rocks-beach.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "indian-shores-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://www.myindianshores.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "international-drive-fl": {
    "chamberUrl": "https://www.orlando.org/",
    "citySiteUrl": "https://www.orangecountyfl.net/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "jacksonville-fl": {
    "chamberUrl": "https://www.myjaxchamber.com/",
    "citySiteUrl": "https://www.jacksonville.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "kissimmee-fl": {
    "chamberUrl": "https://www.kissimmeechamber.com/",
    "citySiteUrl": "https://www.kissimmee.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "lake-buena-vista-fl": {
    "chamberUrl": "https://www.orlando.org/",
    "citySiteUrl": "https://www.orangecountyfl.net/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "lake-mary-fl": {
    "chamberUrl": "https://www.seminolebusiness.org/",
    "citySiteUrl": "https://www.lakemaryfl.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "lakeland-fl": {
    "chamberUrl": "https://www.lakelandchamber.com/",
    "citySiteUrl": "https://www.lakelandgov.net/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "land-o-lakes-fl": {
    "chamberUrl": "https://www.pascochamber.com/",
    "citySiteUrl": "https://www.pascocountyfl.net/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "largo-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://www.largo.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "leesburg-fl": {
    "chamberUrl": "https://www.leesburgchamber.com/",
    "citySiteUrl": "https://www.leesburgflorida.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "lithia-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://hcfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "longwood-fl": {
    "chamberUrl": "https://www.seminolebusiness.org/",
    "citySiteUrl": "https://www.longwoodfl.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "lutz-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://hcfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "madeira-beach-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://www.madeirabeachfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "maitland-fl": {
    "chamberUrl": "https://www.maitland.org/",
    "citySiteUrl": "https://www.itsmymaitland.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "mango-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://hcfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "miami-fl": {
    "chamberUrl": "https://www.miamichamber.com/",
    "citySiteUrl": "https://www.miami.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "minneola-fl": {
    "chamberUrl": "https://www.southlakechamber-fl.com/",
    "citySiteUrl": "https://www.minneola.us/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "miramar-fl": {
    "chamberUrl": "https://www.miramarpembrokechamber.com/",
    "citySiteUrl": "https://www.miramarfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "mount-dora-fl": {
    "chamberUrl": "https://www.mountdora.com/",
    "citySiteUrl": "https://www.cityofmountdora.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "new-port-richey-fl": {
    "chamberUrl": "https://www.westpascochamber.org/",
    "citySiteUrl": "https://www.cityofnewportrichey.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "new-tampa-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://www.tampa.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "ocoee-fl": {
    "chamberUrl": "https://www.wocchamber.com/",
    "citySiteUrl": "https://www.ocoee.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "odessa-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://hcfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "oldsmar-fl": {
    "chamberUrl": "https://www.uppertampabaychamber.com/",
    "citySiteUrl": "https://www.myoldsmar.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "orlando-fl": {
    "chamberUrl": "https://www.orlando.org/",
    "citySiteUrl": "https://www.orlando.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "oviedo-fl": {
    "chamberUrl": "https://www.oviedowintersprings.org/",
    "citySiteUrl": "https://www.cityofoviedo.net/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "palm-bay-fl": {
    "chamberUrl": "https://www.greaterpalmbaychamber.com/",
    "citySiteUrl": "https://www.palmbayflorida.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "palm-coast-fl": {
    "chamberUrl": "https://www.palmcoastchamber.com/",
    "citySiteUrl": "https://www.palmcoastgov.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "palm-harbor-fl": {
    "chamberUrl": "https://www.palmharborcc.org/",
    "citySiteUrl": "https://pinellas.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "pass-a-grille-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://pinellas.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "pembroke-pines-fl": {
    "chamberUrl": "https://www.miramarpembrokechamber.com/",
    "citySiteUrl": "https://www.ppines.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "pensacola-fl": {
    "chamberUrl": "https://www.pensacolachamber.com/",
    "citySiteUrl": "https://www.cityofpensacola.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "pine-hills-fl": {
    "chamberUrl": "https://www.orlando.org/",
    "citySiteUrl": "https://www.orangecountyfl.net/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "pinellas-park-fl": {
    "chamberUrl": "https://www.pinellasparkchamber.com/",
    "citySiteUrl": "https://www.pinellas-park.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "plant-city-fl": {
    "chamberUrl": "https://www.plantcity.org/",
    "citySiteUrl": "https://www.plantcitygov.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "plantation-fl": {
    "chamberUrl": "https://www.plantationchamber.org/",
    "citySiteUrl": "https://www.plantation.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "poinciana-fl": {
    "chamberUrl": "https://www.kissimmeechamber.com/",
    "citySiteUrl": "https://www.osceola.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "pompano-beach-fl": {
    "chamberUrl": "https://www.pompanobeachchamber.com/",
    "citySiteUrl": "https://www.pompanobeachfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "port-richey-fl": {
    "chamberUrl": "https://www.westpascochamber.org/",
    "citySiteUrl": "https://www.cityofportrichey.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "port-st-lucie-fl": {
    "chamberUrl": "https://www.stluciechamber.org/",
    "citySiteUrl": "https://www.cityofpsl.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "redington-beach-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://www.townofredingtonbeach.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "redington-shores-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://www.townofredingtonshores.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "riverview-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://hcfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "ruskin-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://hcfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "safety-harbor-fl": {
    "chamberUrl": "https://www.safetyharborchamber.com/",
    "citySiteUrl": "https://www.cityofsafetyharbor.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "sanford-fl": {
    "chamberUrl": "https://www.seminolebusiness.org/",
    "citySiteUrl": "https://www.sanfordfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "seffner-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://hcfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "seminole-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://www.myseminole.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "south-pasadena-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://mysouthpasadena.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "spring-hill-fl": {
    "chamberUrl": "https://www.hernandochamber.com/",
    "citySiteUrl": "https://www.hernandocounty.us/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "st-cloud-fl": {
    "chamberUrl": "https://www.stcloudflchamber.com/",
    "citySiteUrl": "https://www.stcloud.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "st-pete-beach-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://www.stpetebeach.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "st-petersburg-fl": {
    "chamberUrl": "https://www.stpete.com/",
    "citySiteUrl": "https://www.stpete.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "sun-city-center-fl": {
    "chamberUrl": "https://www.southshorechamberofcommerce.org/",
    "citySiteUrl": "https://hcfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "sunrise-fl": {
    "chamberUrl": "https://www.sunrisechamber.org/",
    "citySiteUrl": "https://www.sunrisefl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "tallahassee-fl": {
    "chamberUrl": "https://www.talchamber.com/",
    "citySiteUrl": "https://www.talgov.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "tampa-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://www.tampa.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "tarpon-springs-fl": {
    "chamberUrl": "https://www.tarponspringschamber.org/",
    "citySiteUrl": "https://www.ctsfl.us/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "tavares-fl": {
    "chamberUrl": "https://www.tavareschamber.com/",
    "citySiteUrl": "https://www.tavares.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "temple-terrace-fl": {
    "chamberUrl": "https://www.templeterracechamber.com/",
    "citySiteUrl": "https://www.templeterrace.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "thonotosassa-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://hcfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "treasure-island-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://www.mytreasureisland.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "trinity-fl": {
    "chamberUrl": "https://www.pascochamber.com/",
    "citySiteUrl": "https://www.pascocountyfl.net/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "union-park-fl": {
    "chamberUrl": "https://www.orlando.org/",
    "citySiteUrl": "https://www.orangecountyfl.net/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "universal-orlando-area-fl": {
    "chamberUrl": "https://www.orlando.org/",
    "citySiteUrl": "https://www.orangecountyfl.net/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "valrico-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://hcfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "weeki-wachee-fl": {
    "chamberUrl": "https://www.hernandochamber.com/",
    "citySiteUrl": "https://www.hernandocounty.us/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "wesley-chapel-fl": {
    "chamberUrl": "https://www.pascochamber.com/",
    "citySiteUrl": "https://www.pascocountyfl.net/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "west-palm-beach-fl": {
    "chamberUrl": "https://www.palmbeaches.org/",
    "citySiteUrl": "https://www.wpb.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "westchase-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://hcfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "wimauma-fl": {
    "chamberUrl": "https://www.tampabaychamber.com/",
    "citySiteUrl": "https://hcfl.gov/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "windermere-fl": {
    "chamberUrl": "https://www.wocchamber.com/",
    "citySiteUrl": "https://www.town.windermere.fl.us/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "winter-garden-fl": {
    "chamberUrl": "https://www.wocchamber.com/",
    "citySiteUrl": "https://www.cwgdn.com/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "winter-park-fl": {
    "chamberUrl": "https://www.winterpark.org/",
    "citySiteUrl": "https://www.cityofwinterpark.org/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "zephyrhills-fl": {
    "chamberUrl": "https://www.zephyrhillschamber.org/",
    "citySiteUrl": "https://www.zephyrhills.net/",
    "stateCommerceUrl": "https://www.floridajobs.org/"
  },
  "athens-ga": {
    "chamberUrl": "https://www.athensga.com/",
    "citySiteUrl": "https://www.athensclarkecounty.com/",
    "stateCommerceUrl": "https://www.georgia.org/"
  },
  "atlanta-ga": {
    "chamberUrl": "https://www.metroatlantachamber.com/",
    "citySiteUrl": "https://www.atlantaga.gov/",
    "stateCommerceUrl": "https://www.georgia.org/"
  },
  "augusta-ga": {
    "chamberUrl": "https://www.augustametrochamber.com/",
    "citySiteUrl": "https://www.augustaga.gov/",
    "stateCommerceUrl": "https://www.georgia.org/"
  },
  "macon-ga": {
    "chamberUrl": "https://www.maconchamber.com/",
    "citySiteUrl": "https://www.maconbibb.us/",
    "stateCommerceUrl": "https://www.georgia.org/"
  },
  "sandy-springs-ga": {
    "chamberUrl": "https://www.sandyspringsperimeterchamber.com/",
    "citySiteUrl": "https://www.sandyspringsga.gov/",
    "stateCommerceUrl": "https://www.georgia.org/"
  },
  "savannah-ga": {
    "chamberUrl": "https://www.savannahchamber.com/",
    "citySiteUrl": "https://www.savannahga.gov/",
    "stateCommerceUrl": "https://www.georgia.org/"
  },
  "honolulu-hi": {
    "chamberUrl": "https://www.cochawaii.org/",
    "citySiteUrl": "https://www.honolulu.gov/",
    "stateCommerceUrl": "https://dbedt.hawaii.gov/"
  },
  "boise-id": {
    "chamberUrl": "https://boisechamber.org/",
    "citySiteUrl": "https://www.cityofboise.org/",
    "stateCommerceUrl": "https://commerce.idaho.gov/"
  },
  "meridian-id": {
    "chamberUrl": "https://www.meridianchamber.org/",
    "citySiteUrl": "https://www.meridiancity.org/",
    "stateCommerceUrl": "https://commerce.idaho.gov/"
  },
  "nampa-id": {
    "chamberUrl": "https://nampa.com/",
    "citySiteUrl": "https://www.cityofnampa.us/",
    "stateCommerceUrl": "https://commerce.idaho.gov/"
  },
  "chicago-il": {
    "chamberUrl": "https://www.chicagolandchamber.org/",
    "citySiteUrl": "https://www.chicago.gov/",
    "stateCommerceUrl": "https://dceo.illinois.gov/"
  },
  "elgin-il": {
    "chamberUrl": "https://www.elginareachamber.com/",
    "citySiteUrl": "https://www.cityofelgin.org/",
    "stateCommerceUrl": "https://dceo.illinois.gov/"
  },
  "joliet-il": {
    "chamberUrl": "https://www.jolietchamber.com/",
    "citySiteUrl": "https://www.joliet.gov/",
    "stateCommerceUrl": "https://dceo.illinois.gov/"
  },
  "naperville-il": {
    "chamberUrl": "https://www.naperville.net/",
    "citySiteUrl": "https://www.naperville.il.us/",
    "stateCommerceUrl": "https://dceo.illinois.gov/"
  },
  "peoria-il": {
    "chamberUrl": "https://www.peoriachamber.org/",
    "citySiteUrl": "https://www.peoriagov.org/",
    "stateCommerceUrl": "https://dceo.illinois.gov/"
  },
  "rockford-il": {
    "chamberUrl": "https://www.rockfordchamber.com/",
    "citySiteUrl": "https://rockfordil.gov/",
    "stateCommerceUrl": "https://dceo.illinois.gov/"
  },
  "springfield-il": {
    "chamberUrl": "https://gscc.org/",
    "citySiteUrl": "https://www.springfield.il.us/",
    "stateCommerceUrl": "https://dceo.illinois.gov/"
  },
  "carmel-in": {
    "chamberUrl": "https://www.carmelchamber.com/",
    "citySiteUrl": "https://www.carmel.in.gov/",
    "stateCommerceUrl": "https://iedc.in.gov/"
  },
  "evansville-in": {
    "chamberUrl": "https://www.evansvillechamber.com/",
    "citySiteUrl": "https://www.evansvillegov.org/",
    "stateCommerceUrl": "https://iedc.in.gov/"
  },
  "fishers-in": {
    "chamberUrl": "https://www.fisherschamber.com/",
    "citySiteUrl": "https://www.fishers.in.us/",
    "stateCommerceUrl": "https://iedc.in.gov/"
  },
  "fort-wayne-in": {
    "chamberUrl": "https://www.fwchamber.org/",
    "citySiteUrl": "https://www.cityoffortwayne.org/",
    "stateCommerceUrl": "https://iedc.in.gov/"
  },
  "gary-in": {
    "chamberUrl": "https://www.garychamber.com/",
    "citySiteUrl": "https://www.gary.gov/",
    "stateCommerceUrl": "https://iedc.in.gov/"
  },
  "indianapolis-in": {
    "chamberUrl": "https://www.indychamber.com/",
    "citySiteUrl": "https://www.indy.gov/",
    "stateCommerceUrl": "https://iedc.in.gov/"
  },
  "south-bend-in": {
    "chamberUrl": "https://www.southbendregionalchamber.com/",
    "citySiteUrl": "https://southbendin.gov/",
    "stateCommerceUrl": "https://iedc.in.gov/"
  },
  "cedar-rapids-ia": {
    "chamberUrl": "https://www.cedarrapids.org/",
    "citySiteUrl": "https://www.cedar-rapids.org/",
    "stateCommerceUrl": "https://opportunityiowa.gov/"
  },
  "davenport-ia": {
    "chamberUrl": "https://www.quadcserfschamber.com/",
    "citySiteUrl": "https://www.davenportiowa.com/",
    "stateCommerceUrl": "https://opportunityiowa.gov/"
  },
  "des-moines-ia": {
    "chamberUrl": "https://www.desmoinesmetro.com/",
    "citySiteUrl": "https://www.dsm.city/",
    "stateCommerceUrl": "https://opportunityiowa.gov/"
  },
  "kansas-city-ks": {
    "chamberUrl": "https://www.kansascityks.org/",
    "citySiteUrl": "https://www.wycokck.org/",
    "stateCommerceUrl": "https://www.kansascommerce.gov/"
  },
  "olathe-ks": {
    "chamberUrl": "https://www.olathe.org/",
    "citySiteUrl": "https://www.olatheks.org/",
    "stateCommerceUrl": "https://www.kansascommerce.gov/"
  },
  "overland-park-ks": {
    "chamberUrl": "https://www.opchamber.org/",
    "citySiteUrl": "https://www.opkansas.org/",
    "stateCommerceUrl": "https://www.kansascommerce.gov/"
  },
  "topeka-ks": {
    "chamberUrl": "https://www.topekachamber.org/",
    "citySiteUrl": "https://www.topeka.org/",
    "stateCommerceUrl": "https://www.kansascommerce.gov/"
  },
  "wichita-ks": {
    "chamberUrl": "https://www.wichitachamber.org/",
    "citySiteUrl": "https://www.wichita.gov/",
    "stateCommerceUrl": "https://www.kansascommerce.gov/"
  },
  "lexington-ky": {
    "chamberUrl": "https://www.commercelexington.com/",
    "citySiteUrl": "https://www.lexingtonky.gov/",
    "stateCommerceUrl": "https://ced.ky.gov/"
  },
  "louisville-ky": {
    "chamberUrl": "https://www.greaterlouisville.com/",
    "citySiteUrl": "https://louisvilleky.gov/",
    "stateCommerceUrl": "https://ced.ky.gov/"
  },
  "baton-rouge-la": {
    "chamberUrl": "https://www.brac.org/",
    "citySiteUrl": "https://www.brla.gov/",
    "stateCommerceUrl": "https://www.opportunitylouisiana.gov/"
  },
  "lafayette-la": {
    "chamberUrl": "https://www.lafchamber.org/",
    "citySiteUrl": "https://www.lafayettela.gov/",
    "stateCommerceUrl": "https://www.opportunitylouisiana.gov/"
  },
  "new-orleans-la": {
    "chamberUrl": "https://www.neworleanschamber.org/",
    "citySiteUrl": "https://nola.gov/",
    "stateCommerceUrl": "https://www.opportunitylouisiana.gov/"
  },
  "shreveport-la": {
    "chamberUrl": "https://www.shreveportchamber.org/",
    "citySiteUrl": "https://www.shreveportla.gov/",
    "stateCommerceUrl": "https://www.opportunitylouisiana.gov/"
  },
  "baltimore-md": {
    "chamberUrl": "https://www.baltimorecountychamber.com/",
    "citySiteUrl": "https://www.baltimorecity.gov/",
    "stateCommerceUrl": "https://commerce.maryland.gov/"
  },
  "boston-ma": {
    "chamberUrl": "https://www.bostonchamber.com/",
    "citySiteUrl": "https://www.boston.gov/",
    "stateCommerceUrl": "https://www.mass.gov/orgs/executive-office-of-economic-development"
  },
  "cambridge-ma": {
    "chamberUrl": "https://www.cambridgechamber.org/",
    "citySiteUrl": "https://www.cambridgema.gov/",
    "stateCommerceUrl": "https://www.mass.gov/orgs/executive-office-of-economic-development"
  },
  "lowell-ma": {
    "chamberUrl": "https://www.greaterlowellchamber.org/",
    "citySiteUrl": "https://www.lowellma.gov/",
    "stateCommerceUrl": "https://www.mass.gov/orgs/executive-office-of-economic-development"
  },
  "new-bedford-ma": {
    "chamberUrl": "https://www.newbedfordchamber.com/",
    "citySiteUrl": "https://www.newbedford-ma.gov/",
    "stateCommerceUrl": "https://www.mass.gov/orgs/executive-office-of-economic-development"
  },
  "quincy-ma": {
    "chamberUrl": "https://quincychamber.org/",
    "citySiteUrl": "https://www.quincyma.gov/",
    "stateCommerceUrl": "https://www.mass.gov/orgs/executive-office-of-economic-development"
  },
  "springfield-ma": {
    "chamberUrl": "https://www.springfieldregionalchamber.com/",
    "citySiteUrl": "https://www.springfield-ma.gov/",
    "stateCommerceUrl": "https://www.mass.gov/orgs/executive-office-of-economic-development"
  },
  "worcester-ma": {
    "chamberUrl": "https://www.worcesterchamber.org/",
    "citySiteUrl": "https://www.worcesterma.gov/",
    "stateCommerceUrl": "https://www.mass.gov/orgs/executive-office-of-economic-development"
  },
  "ann-arbor-mi": {
    "chamberUrl": "https://www.a2ychamber.org/",
    "citySiteUrl": "https://www.a2gov.org/",
    "stateCommerceUrl": "https://www.michiganbusiness.org/"
  },
  "dearborn-mi": {
    "chamberUrl": "https://www.dearbornareachamber.org/",
    "citySiteUrl": "https://www.dearborn.gov/",
    "stateCommerceUrl": "https://www.michiganbusiness.org/"
  },
  "detroit-mi": {
    "chamberUrl": "https://www.detroitchamber.com/",
    "citySiteUrl": "https://detroitmi.gov/",
    "stateCommerceUrl": "https://www.michiganbusiness.org/"
  },
  "grand-rapids-mi": {
    "chamberUrl": "https://www.grandrapids.org/",
    "citySiteUrl": "https://www.grandrapidsmi.gov/",
    "stateCommerceUrl": "https://www.michiganbusiness.org/"
  },
  "lansing-mi": {
    "chamberUrl": "https://www.lansingchamber.org/",
    "citySiteUrl": "https://www.lansingmi.gov/",
    "stateCommerceUrl": "https://www.michiganbusiness.org/"
  },
  "livonia-mi": {
    "chamberUrl": "https://www.livonia.org/",
    "citySiteUrl": "https://www.livonia.gov/",
    "stateCommerceUrl": "https://www.michiganbusiness.org/"
  },
  "sterling-heights-mi": {
    "chamberUrl": "https://www.shchamber.com/",
    "citySiteUrl": "https://www.sterlingheights.gov/",
    "stateCommerceUrl": "https://www.michiganbusiness.org/"
  },
  "troy-mi": {
    "chamberUrl": "https://www.troychamber.com/",
    "citySiteUrl": "https://www.troymi.gov/",
    "stateCommerceUrl": "https://www.michiganbusiness.org/"
  },
  "warren-mi": {
    "chamberUrl": "https://www.warrenchamber.com/",
    "citySiteUrl": "https://www.cityofwarren.org/",
    "stateCommerceUrl": "https://www.michiganbusiness.org/"
  },
  "bloomington-mn": {
    "chamberUrl": "https://www.bloomingtonmnchamber.com/",
    "citySiteUrl": "https://www.bloomingtonmn.gov/",
    "stateCommerceUrl": "https://mn.gov/deed/"
  },
  "duluth-mn": {
    "chamberUrl": "https://www.duluthchamber.com/",
    "citySiteUrl": "https://duluthmn.gov/",
    "stateCommerceUrl": "https://mn.gov/deed/"
  },
  "eagan-mn": {
    "chamberUrl": "https://www.dcrchamber.com/",
    "citySiteUrl": "https://www.eaganmn.gov/",
    "stateCommerceUrl": "https://mn.gov/deed/"
  },
  "minneapolis-mn": {
    "chamberUrl": "https://www.mplschamber.com/",
    "citySiteUrl": "https://www.minneapolismn.gov/",
    "stateCommerceUrl": "https://mn.gov/deed/"
  },
  "rochester-mn": {
    "chamberUrl": "https://www.rochestermnchamber.com/",
    "citySiteUrl": "https://www.rochestermn.gov/",
    "stateCommerceUrl": "https://mn.gov/deed/"
  },
  "st-paul-mn": {
    "chamberUrl": "https://www.saintpaulchamber.com/",
    "citySiteUrl": "https://www.stpaul.gov/",
    "stateCommerceUrl": "https://mn.gov/deed/"
  },
  "independence-mo": {
    "chamberUrl": "https://www.independencechamber.com/",
    "citySiteUrl": "https://www.ci.independence.mo.us/",
    "stateCommerceUrl": "https://ded.mo.gov/"
  },
  "kansas-city-mo": {
    "chamberUrl": "https://www.kcchamber.com/",
    "citySiteUrl": "https://www.kcmo.gov/",
    "stateCommerceUrl": "https://ded.mo.gov/"
  },
  "lee-summit-mo": {
    "chamberUrl": "https://www.lschamber.com/",
    "citySiteUrl": "https://cityofls.net/",
    "stateCommerceUrl": "https://ded.mo.gov/"
  },
  "o-fallon-mo": {
    "chamberUrl": "https://ofallonchamber.org/",
    "citySiteUrl": "https://www.ofallon.mo.us/",
    "stateCommerceUrl": "https://ded.mo.gov/"
  },
  "springfield-mo": {
    "chamberUrl": "https://www.springfieldchamber.com/",
    "citySiteUrl": "https://www.springfieldmo.gov/",
    "stateCommerceUrl": "https://ded.mo.gov/"
  },
  "st-louis-mo": {
    "chamberUrl": "https://www.stlregionalchamber.com/",
    "citySiteUrl": "https://www.stlouis-mo.gov/",
    "stateCommerceUrl": "https://ded.mo.gov/"
  },
  "billings-mt": {
    "chamberUrl": "https://www.billingschamber.com/",
    "citySiteUrl": "https://www.billingsmt.gov/",
    "stateCommerceUrl": "https://commerce.mt.gov/"
  },
  "lincoln-ne": {
    "chamberUrl": "https://www.lcoc.com/",
    "citySiteUrl": "https://www.lincoln.ne.gov/",
    "stateCommerceUrl": "https://opportunity.nebraska.gov/"
  },
  "omaha-ne": {
    "chamberUrl": "https://www.omahachamber.org/",
    "citySiteUrl": "https://www.cityofomaha.org/",
    "stateCommerceUrl": "https://opportunity.nebraska.gov/"
  },
  "henderson-nv": {
    "chamberUrl": "https://www.hendersonchamber.com/",
    "citySiteUrl": "https://www.cityofhenderson.com/",
    "stateCommerceUrl": "https://goed.nv.gov/"
  },
  "las-vegas-nv": {
    "chamberUrl": "https://www.vegaschamber.com/",
    "citySiteUrl": "https://www.lasvegasnevada.gov/",
    "stateCommerceUrl": "https://goed.nv.gov/"
  },
  "north-las-vegas-nv": {
    "chamberUrl": "https://www.northlasvegaschamber.com/",
    "citySiteUrl": "https://www.cityofnorthlasvegas.com/",
    "stateCommerceUrl": "https://goed.nv.gov/"
  },
  "reno-nv": {
    "chamberUrl": "https://thechambernv.org/",
    "citySiteUrl": "https://www.reno.gov/",
    "stateCommerceUrl": "https://goed.nv.gov/"
  },
  "sparks-nv": {
    "chamberUrl": "https://thechambernv.org/",
    "citySiteUrl": "https://www.cityofsparks.us/",
    "stateCommerceUrl": "https://goed.nv.gov/"
  },
  "edison-nj": {
    "chamberUrl": "https://www.edisonchamber.com/",
    "citySiteUrl": "https://www.edisonnj.org/",
    "stateCommerceUrl": "https://www.njeda.gov/"
  },
  "elizabeth-nj": {
    "chamberUrl": "https://www.elizabethnjchamber.com/",
    "citySiteUrl": "https://www.elizabethnj.org/",
    "stateCommerceUrl": "https://www.njeda.gov/"
  },
  "jersey-city-nj": {
    "chamberUrl": "https://www.jcchamber.org/",
    "citySiteUrl": "https://www.jerseycitynj.gov/",
    "stateCommerceUrl": "https://www.njeda.gov/"
  },
  "lakewood-nj": {
    "chamberUrl": "https://www.mtccnj.com/",
    "citySiteUrl": "https://www.lakewoodnj.gov/",
    "stateCommerceUrl": "https://www.njeda.gov/"
  },
  "newark-nj": {
    "chamberUrl": "https://www.newarkregionalbusiness.com/",
    "citySiteUrl": "https://www.newarknj.gov/",
    "stateCommerceUrl": "https://www.njeda.gov/"
  },
  "paterson-nj": {
    "chamberUrl": "https://www.greaterpatersoncc.org/",
    "citySiteUrl": "https://www.patersonnj.gov/",
    "stateCommerceUrl": "https://www.njeda.gov/"
  },
  "woodbridge-nj": {
    "chamberUrl": "https://www.woodbridgechamber.com/",
    "citySiteUrl": "https://www.twp.woodbridge.nj.us/",
    "stateCommerceUrl": "https://www.njeda.gov/"
  },
  "albuquerque-nm": {
    "chamberUrl": "https://www.abqchamber.com/",
    "citySiteUrl": "https://www.cabq.gov/",
    "stateCommerceUrl": "https://edd.newmexico.gov/"
  },
  "las-cruces-nm": {
    "chamberUrl": "https://www.lascruces.org/",
    "citySiteUrl": "https://www.las-cruces.org/",
    "stateCommerceUrl": "https://edd.newmexico.gov/"
  },
  "rio-rancho-nm": {
    "chamberUrl": "https://www.rrrcc.org/",
    "citySiteUrl": "https://rrnm.gov/",
    "stateCommerceUrl": "https://edd.newmexico.gov/"
  },
  "santa-fe-nm": {
    "chamberUrl": "https://www.santafechamber.com/",
    "citySiteUrl": "https://www.santafenm.gov/",
    "stateCommerceUrl": "https://edd.newmexico.gov/"
  },
  "buffalo-ny": {
    "chamberUrl": "https://www.thepartnership.org/",
    "citySiteUrl": "https://www.buffalony.gov/",
    "stateCommerceUrl": "https://esd.ny.gov/"
  },
  "new-york-ny": {
    "chamberUrl": "https://www.nychamber.com/",
    "citySiteUrl": "https://www.nyc.gov/",
    "stateCommerceUrl": "https://esd.ny.gov/"
  },
  "rochester-ny": {
    "chamberUrl": "https://www.greaterrochesterchamber.com/",
    "citySiteUrl": "https://www.cityofrochester.gov/",
    "stateCommerceUrl": "https://esd.ny.gov/"
  },
  "yonkers-ny": {
    "chamberUrl": "https://www.yonkerschamber.com/",
    "citySiteUrl": "https://www.yonkersny.gov/",
    "stateCommerceUrl": "https://esd.ny.gov/"
  },
  "cary-nc": {
    "chamberUrl": "https://www.carychamber.com/",
    "citySiteUrl": "https://www.carync.gov/",
    "stateCommerceUrl": "https://www.commerce.nc.gov/"
  },
  "charlotte-nc": {
    "chamberUrl": "https://charlottechamber.com/",
    "citySiteUrl": "https://www.charlottenc.gov/",
    "stateCommerceUrl": "https://www.commerce.nc.gov/"
  },
  "durham-nc": {
    "chamberUrl": "https://www.durhamchamber.org/",
    "citySiteUrl": "https://www.durhamnc.gov/",
    "stateCommerceUrl": "https://www.commerce.nc.gov/"
  },
  "fayetteville-nc": {
    "chamberUrl": "https://www.faybiz.com/",
    "citySiteUrl": "https://www.fayettevillenc.gov/",
    "stateCommerceUrl": "https://www.commerce.nc.gov/"
  },
  "greensboro-nc": {
    "chamberUrl": "https://www.greensboro.org/",
    "citySiteUrl": "https://www.greensboro-nc.gov/",
    "stateCommerceUrl": "https://www.commerce.nc.gov/"
  },
  "high-point-nc": {
    "chamberUrl": "https://www.highpointchamber.org/",
    "citySiteUrl": "https://www.highpointnc.gov/",
    "stateCommerceUrl": "https://www.commerce.nc.gov/"
  },
  "raleigh-nc": {
    "chamberUrl": "https://www.raleighchamber.org/",
    "citySiteUrl": "https://www.raleighnc.gov/",
    "stateCommerceUrl": "https://www.commerce.nc.gov/"
  },
  "wilmington-nc": {
    "chamberUrl": "https://www.wilmingtonchamber.org/",
    "citySiteUrl": "https://www.wilmingtonnc.gov/",
    "stateCommerceUrl": "https://www.commerce.nc.gov/"
  },
  "winston-salem-nc": {
    "chamberUrl": "https://www.winstonsalem.com/",
    "citySiteUrl": "https://www.cityofws.org/",
    "stateCommerceUrl": "https://www.commerce.nc.gov/"
  },
  "fargo-nd": {
    "chamberUrl": "https://www.fmwfchamber.com/",
    "citySiteUrl": "https://www.fargond.gov/",
    "stateCommerceUrl": "https://www.commerce.nd.gov/"
  },
  "akron-oh": {
    "chamberUrl": "https://www.greaterakronchamber.org/",
    "citySiteUrl": "https://www.akronohio.gov/",
    "stateCommerceUrl": "https://development.ohio.gov/"
  },
  "cincinnati-oh": {
    "chamberUrl": "https://www.cincinnatichamber.com/",
    "citySiteUrl": "https://www.cincinnati-oh.gov/",
    "stateCommerceUrl": "https://development.ohio.gov/"
  },
  "cleveland-oh": {
    "chamberUrl": "https://www.gcpartnership.com/",
    "citySiteUrl": "https://www.clevelandohio.gov/",
    "stateCommerceUrl": "https://development.ohio.gov/"
  },
  "columbus-oh": {
    "chamberUrl": "https://columbus.org/",
    "citySiteUrl": "https://www.columbus.gov/",
    "stateCommerceUrl": "https://development.ohio.gov/"
  },
  "dayton-oh": {
    "chamberUrl": "https://www.daytonchamber.org/",
    "citySiteUrl": "https://www.daytonohio.gov/",
    "stateCommerceUrl": "https://development.ohio.gov/"
  },
  "parma-oh": {
    "chamberUrl": "https://www.parmaareachamber.org/",
    "citySiteUrl": "https://www.cityofparma-oh.gov/",
    "stateCommerceUrl": "https://development.ohio.gov/"
  },
  "toledo-oh": {
    "chamberUrl": "https://www.toledochamber.com/",
    "citySiteUrl": "https://toledo.oh.gov/",
    "stateCommerceUrl": "https://development.ohio.gov/"
  },
  "broken-arrow-ok": {
    "chamberUrl": "https://www.brokenarrowchamber.com/",
    "citySiteUrl": "https://www.brokenarrowok.gov/",
    "stateCommerceUrl": "https://www.okcommerce.gov/"
  },
  "norman-ok": {
    "chamberUrl": "https://www.normanchamber.com/",
    "citySiteUrl": "https://www.normanok.gov/",
    "stateCommerceUrl": "https://www.okcommerce.gov/"
  },
  "oklahoma-city-ok": {
    "chamberUrl": "https://www.okcchamber.com/",
    "citySiteUrl": "https://www.okc.gov/",
    "stateCommerceUrl": "https://www.okcommerce.gov/"
  },
  "tulsa-ok": {
    "chamberUrl": "https://www.tulsachamber.com/",
    "citySiteUrl": "https://www.cityoftulsa.org/",
    "stateCommerceUrl": "https://www.okcommerce.gov/"
  },
  "bend-or": {
    "chamberUrl": "https://www.bendchamber.org/",
    "citySiteUrl": "https://www.bendoregon.gov/",
    "stateCommerceUrl": "https://www.oregon.gov/biz/"
  },
  "eugene-or": {
    "chamberUrl": "https://www.eugenechamber.com/",
    "citySiteUrl": "https://www.eugene-or.gov/",
    "stateCommerceUrl": "https://www.oregon.gov/biz/"
  },
  "gresham-or": {
    "chamberUrl": "https://www.greshamchamber.org/",
    "citySiteUrl": "https://greshamoregon.gov/",
    "stateCommerceUrl": "https://www.oregon.gov/biz/"
  },
  "portland-or": {
    "chamberUrl": "https://portlandalliance.com/",
    "citySiteUrl": "https://www.portland.gov/",
    "stateCommerceUrl": "https://www.oregon.gov/biz/"
  },
  "salem-or": {
    "chamberUrl": "https://www.salemchamber.org/",
    "citySiteUrl": "https://www.cityofsalem.net/",
    "stateCommerceUrl": "https://www.oregon.gov/biz/"
  },
  "allentown-pa": {
    "chamberUrl": "https://www.lehighvalleychamber.org/",
    "citySiteUrl": "https://www.allentownpa.gov/",
    "stateCommerceUrl": "https://dced.pa.gov/"
  },
  "philadelphia-pa": {
    "chamberUrl": "https://chamberphl.com/",
    "citySiteUrl": "https://www.phila.gov/",
    "stateCommerceUrl": "https://dced.pa.gov/"
  },
  "pittsburgh-pa": {
    "chamberUrl": "https://www.alleghenyconference.org/",
    "citySiteUrl": "https://pittsburghpa.gov/",
    "stateCommerceUrl": "https://dced.pa.gov/"
  },
  "providence-ri": {
    "chamberUrl": "https://www.provchamber.com/",
    "citySiteUrl": "https://www.providenceri.gov/",
    "stateCommerceUrl": "https://commerceri.com/"
  },
  "charleston-sc": {
    "chamberUrl": "https://www.charlestonchamber.org/",
    "citySiteUrl": "https://www.charleston-sc.gov/",
    "stateCommerceUrl": "https://www.sccommerce.com/"
  },
  "columbia-sc": {
    "chamberUrl": "https://www.columbiachamber.com/",
    "citySiteUrl": "https://www.columbiasc.gov/",
    "stateCommerceUrl": "https://www.sccommerce.com/"
  },
  "rapid-city-sd": {
    "chamberUrl": "https://www.rapidcitychamber.com/",
    "citySiteUrl": "https://www.rcgov.org/",
    "stateCommerceUrl": "https://sdgoed.com/"
  },
  "sioux-falls-sd": {
    "chamberUrl": "https://www.siouxfallschamber.com/",
    "citySiteUrl": "https://www.siouxfalls.gov/",
    "stateCommerceUrl": "https://sdgoed.com/"
  },
  "chattanooga-tn": {
    "chamberUrl": "https://www.chattanoogachamber.com/",
    "citySiteUrl": "https://www.chattanooga.gov/",
    "stateCommerceUrl": "https://www.tn.gov/ecd/"
  },
  "clarksville-tn": {
    "chamberUrl": "https://www.clarksville.tn.us/",
    "citySiteUrl": "https://www.cityofclarksville.com/",
    "stateCommerceUrl": "https://www.tn.gov/ecd/"
  },
  "knoxville-tn": {
    "chamberUrl": "https://www.knoxvillechamber.com/",
    "citySiteUrl": "https://www.knoxvilletn.gov/",
    "stateCommerceUrl": "https://www.tn.gov/ecd/"
  },
  "memphis-tn": {
    "chamberUrl": "https://www.memphischamber.com/",
    "citySiteUrl": "https://www.memphistn.gov/",
    "stateCommerceUrl": "https://www.tn.gov/ecd/"
  },
  "murfreesboro-tn": {
    "chamberUrl": "https://www.rutherfordchamber.org/",
    "citySiteUrl": "https://www.murfreesborotn.gov/",
    "stateCommerceUrl": "https://www.tn.gov/ecd/"
  },
  "nashville-tn": {
    "chamberUrl": "https://www.nashvillechamber.com/",
    "citySiteUrl": "https://www.nashville.gov/",
    "stateCommerceUrl": "https://www.tn.gov/ecd/"
  },
  "abilene-tx": {
    "chamberUrl": "https://www.abilenechamber.com/",
    "citySiteUrl": "https://www.abilenetx.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "allen-tx": {
    "chamberUrl": "https://www.allenchamber.com/",
    "citySiteUrl": "https://www.cityofallen.org/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "amarillo-tx": {
    "chamberUrl": "https://www.amarillo-chamber.org/",
    "citySiteUrl": "https://www.amarillo.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "arlington-tx": {
    "chamberUrl": "https://www.arlingtontx.com/",
    "citySiteUrl": "https://www.arlingtontx.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "austin-tx": {
    "chamberUrl": "https://www.austinchamber.com/",
    "citySiteUrl": "https://www.austintexas.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "brownsville-tx": {
    "chamberUrl": "https://www.brownsvillechamber.com/",
    "citySiteUrl": "https://www.brownsvilletx.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "carrollton-tx": {
    "chamberUrl": "https://www.metrocrestchamber.com/",
    "citySiteUrl": "https://www.cityofcarrollton.com/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "college-station-tx": {
    "chamberUrl": "https://www.bcschamber.org/",
    "citySiteUrl": "https://www.cstx.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "conroe-tx": {
    "chamberUrl": "https://www.conroe.org/",
    "citySiteUrl": "https://www.cityofconroe.org/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "corpus-christi-tx": {
    "chamberUrl": "https://www.corpuschristichamber.org/",
    "citySiteUrl": "https://www.cctexas.com/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "dallas-tx": {
    "chamberUrl": "https://www.dallaschamber.org/",
    "citySiteUrl": "https://www.dallascityhall.com/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "denton-tx": {
    "chamberUrl": "https://www.dentonchamber.org/",
    "citySiteUrl": "https://www.cityofdenton.com/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "edinburg-tx": {
    "chamberUrl": "https://www.edinburg.com/",
    "citySiteUrl": "https://www.cityofedinburg.com/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "el-paso-tx": {
    "chamberUrl": "https://www.elpaso.org/",
    "citySiteUrl": "https://www.elpasotexas.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "fort-worth-tx": {
    "chamberUrl": "https://www.fortworthchamber.com/",
    "citySiteUrl": "https://www.fortworthtexas.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "frisco-tx": {
    "chamberUrl": "https://www.friscochamber.com/",
    "citySiteUrl": "https://www.friscotexas.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "garland-tx": {
    "chamberUrl": "https://www.garlandchamber.com/",
    "citySiteUrl": "https://www.garlandtx.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "grand-prairie-tx": {
    "chamberUrl": "https://www.grandprairiechamber.org/",
    "citySiteUrl": "https://www.gptx.org/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "houston-tx": {
    "chamberUrl": "https://www.houston.org/",
    "citySiteUrl": "https://www.houstontx.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "irving-tx": {
    "chamberUrl": "https://www.irvingchamber.com/",
    "citySiteUrl": "https://www.cityofirving.org/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "killeen-tx": {
    "chamberUrl": "https://www.killeenchamber.com/",
    "citySiteUrl": "https://www.killeentexas.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "laredo-tx": {
    "chamberUrl": "https://www.laredochamber.com/",
    "citySiteUrl": "https://www.cityoflaredo.com/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "league-city-tx": {
    "chamberUrl": "https://www.leaguecitychamber.com/",
    "citySiteUrl": "https://www.leaguecitytx.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "lewisville-tx": {
    "chamberUrl": "https://www.lewisvillechamber.com/",
    "citySiteUrl": "https://www.cityoflewisville.com/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "lubbock-tx": {
    "chamberUrl": "https://www.lubbockchamber.com/",
    "citySiteUrl": "https://www.mylubbock.us/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "mcallen-tx": {
    "chamberUrl": "https://www.mcallenchamber.com/",
    "citySiteUrl": "https://www.mcallen.net/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "mckinney-tx": {
    "chamberUrl": "https://www.mckinneychamber.com/",
    "citySiteUrl": "https://www.mckinneytexas.org/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "mesquite-tx": {
    "chamberUrl": "https://www.mesquitechamber.com/",
    "citySiteUrl": "https://www.cityofmesquite.com/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "midland-tx": {
    "chamberUrl": "https://www.midlandtxchamber.com/",
    "citySiteUrl": "https://www.midlandtexas.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "mission-tx": {
    "chamberUrl": "https://www.missionchamber.com/",
    "citySiteUrl": "https://www.missiontexas.us/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "odessa-tx": {
    "chamberUrl": "https://www.odessachamber.com/",
    "citySiteUrl": "https://www.odessa-tx.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "pasadena-tx": {
    "chamberUrl": "https://www.pasadenachamber.org/",
    "citySiteUrl": "https://www.pasadenatx.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "pearland-tx": {
    "chamberUrl": "https://www.pearlandchamber.com/",
    "citySiteUrl": "https://www.pearlandtx.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "plano-tx": {
    "chamberUrl": "https://www.planochamber.org/",
    "citySiteUrl": "https://www.plano.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "round-rock-tx": {
    "chamberUrl": "https://www.roundrockchamber.org/",
    "citySiteUrl": "https://www.roundrocktexas.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "san-antonio-tx": {
    "chamberUrl": "https://www.sachamber.org/",
    "citySiteUrl": "https://www.sanantonio.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "tyler-tx": {
    "chamberUrl": "https://www.tylertexas.com/",
    "citySiteUrl": "https://www.tylertexas.com/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "waco-tx": {
    "chamberUrl": "https://www.wacochamber.com/",
    "citySiteUrl": "https://www.waco-texas.com/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "wichita-falls-tx": {
    "chamberUrl": "https://www.wichitafallschamber.com/",
    "citySiteUrl": "https://www.wichitafallstx.gov/",
    "stateCommerceUrl": "https://gov.texas.gov/business"
  },
  "provo-ut": {
    "chamberUrl": "https://www.thechamber.org/",
    "citySiteUrl": "https://www.provo.gov/",
    "stateCommerceUrl": "https://business.utah.gov/"
  },
  "salt-lake-city-ut": {
    "chamberUrl": "https://slchamber.com/",
    "citySiteUrl": "https://www.slc.gov/",
    "stateCommerceUrl": "https://business.utah.gov/"
  },
  "west-jordan-ut": {
    "chamberUrl": "https://www.westjordanchamber.com/",
    "citySiteUrl": "https://www.westjordan.utah.gov/",
    "stateCommerceUrl": "https://business.utah.gov/"
  },
  "west-valley-city-ut": {
    "chamberUrl": "https://www.chamberwest.com/",
    "citySiteUrl": "https://www.wvc-ut.gov/",
    "stateCommerceUrl": "https://business.utah.gov/"
  },
  "alexandria-va": {
    "chamberUrl": "https://www.thechamberalx.com/",
    "citySiteUrl": "https://www.alexandriava.gov/",
    "stateCommerceUrl": "https://www.vedp.org/"
  },
  "chesapeake-va": {
    "chamberUrl": "https://www.hrchamber.com/",
    "citySiteUrl": "https://www.cityofchesapeake.net/",
    "stateCommerceUrl": "https://www.vedp.org/"
  },
  "norfolk-va": {
    "chamberUrl": "https://www.hrchamber.com/",
    "citySiteUrl": "https://www.norfolk.gov/",
    "stateCommerceUrl": "https://www.vedp.org/"
  },
  "portsmouth-va": {
    "chamberUrl": "https://www.hrchamber.com/",
    "citySiteUrl": "https://www.portsmouthva.gov/",
    "stateCommerceUrl": "https://www.vedp.org/"
  },
  "richmond-va": {
    "chamberUrl": "https://www.richmondchamber.org/",
    "citySiteUrl": "https://www.rva.gov/",
    "stateCommerceUrl": "https://www.vedp.org/"
  },
  "virginia-beach-va": {
    "chamberUrl": "https://www.hrchamber.com/",
    "citySiteUrl": "https://www.virginiabeach.gov/",
    "stateCommerceUrl": "https://www.vedp.org/"
  },
  "bellevue-wa": {
    "chamberUrl": "https://www.bellevuechamber.org/",
    "citySiteUrl": "https://bellevuewa.gov/",
    "stateCommerceUrl": "https://www.commerce.wa.gov/"
  },
  "bellingham-wa": {
    "chamberUrl": "https://www.bellingham.com/",
    "citySiteUrl": "https://cob.org/",
    "stateCommerceUrl": "https://www.commerce.wa.gov/"
  },
  "federal-way-wa": {
    "chamberUrl": "https://www.federalwaychamber.com/",
    "citySiteUrl": "https://www.federalwaywa.gov/",
    "stateCommerceUrl": "https://www.commerce.wa.gov/"
  },
  "kent-wa": {
    "chamberUrl": "https://www.kentchamber.com/",
    "citySiteUrl": "https://www.kentwa.gov/",
    "stateCommerceUrl": "https://www.commerce.wa.gov/"
  },
  "renton-wa": {
    "chamberUrl": "https://gorenton.com/",
    "citySiteUrl": "https://www.rentonwa.gov/",
    "stateCommerceUrl": "https://www.commerce.wa.gov/"
  },
  "seattle-wa": {
    "chamberUrl": "https://www.seattlechamber.com/",
    "citySiteUrl": "https://www.seattle.gov/",
    "stateCommerceUrl": "https://www.commerce.wa.gov/"
  },
  "spokane-wa": {
    "chamberUrl": "https://greaterspokane.org/",
    "citySiteUrl": "https://my.spokanecity.org/",
    "stateCommerceUrl": "https://www.commerce.wa.gov/"
  },
  "spokane-valley-wa": {
    "chamberUrl": "https://www.spokanevalleychamber.org/",
    "citySiteUrl": "https://www.spokanevalleywa.gov/",
    "stateCommerceUrl": "https://www.commerce.wa.gov/"
  },
  "tacoma-wa": {
    "chamberUrl": "https://www.tacomachamber.org/",
    "citySiteUrl": "https://www.cityoftacoma.org/",
    "stateCommerceUrl": "https://www.commerce.wa.gov/"
  },
  "vancouver-wa": {
    "chamberUrl": "https://www.vancouverusa.com/",
    "citySiteUrl": "https://www.cityofvancouver.us/",
    "stateCommerceUrl": "https://www.commerce.wa.gov/"
  },
  "green-bay-wi": {
    "chamberUrl": "https://www.greatergbc.org/",
    "citySiteUrl": "https://greenbaywi.gov/",
    "stateCommerceUrl": "https://wedc.org/"
  },
  "kenosha-wi": {
    "chamberUrl": "https://www.kenoshaarea.com/",
    "citySiteUrl": "https://www.kenosha.org/",
    "stateCommerceUrl": "https://wedc.org/"
  },
  "madison-wi": {
    "chamberUrl": "https://www.greatermadisonchamber.com/",
    "citySiteUrl": "https://www.cityofmadison.com/",
    "stateCommerceUrl": "https://wedc.org/"
  },
  "milwaukee-wi": {
    "chamberUrl": "https://www.mmac.org/",
    "citySiteUrl": "https://city.milwaukee.gov/",
    "stateCommerceUrl": "https://wedc.org/"
  },
  "racine-wi": {
    "chamberUrl": "https://www.racinechamber.com/",
    "citySiteUrl": "https://www.cityofracine.org/",
    "stateCommerceUrl": "https://wedc.org/"
  },
  "pomona-ca-1": {
    "chamberUrl": "https://www.westcovinachamber.com/",
    "citySiteUrl": "https://www.westcovina.org/",
    "stateCommerceUrl": "https://business.ca.gov/"
  }
};

export function getCityResourceLinks(citySlug: string): CityResourceLinks | undefined {
  return CITY_RESOURCE_LINKS[citySlug];
}
