// Top 350 US Cities by Population (2024 Census Estimates)
// Organized by tier for programmatic SEO strategy

export interface USCity {
  slug: string;
  city: string;
  state: string;
  stateCode: string;
  population: number;
  tier: 'major' | 'large' | 'medium' | 'small';
  region: 'Northeast' | 'Southeast' | 'Midwest' | 'Southwest' | 'West';
  latitude: number;
  longitude: number;
  metro?: string;
}

// Tier 1: Major Cities (Pop 500K+) - 35 cities
const majorCities: USCity[] = [
  { slug: "new-york-ny", city: "New York", state: "New York", stateCode: "NY", population: 8336817, tier: "major", region: "Northeast", latitude: 40.7128, longitude: -74.0060, metro: "New York-Newark-Jersey City" },
  { slug: "los-angeles-ca", city: "Los Angeles", state: "California", stateCode: "CA", population: 3979576, tier: "major", region: "West", latitude: 34.0522, longitude: -118.2437, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "chicago-il", city: "Chicago", state: "Illinois", stateCode: "IL", population: 2693976, tier: "major", region: "Midwest", latitude: 41.8781, longitude: -87.6298, metro: "Chicago-Naperville-Elgin" },
  { slug: "houston-tx", city: "Houston", state: "Texas", stateCode: "TX", population: 2304580, tier: "major", region: "Southwest", latitude: 29.7604, longitude: -95.3698, metro: "Houston-The Woodlands-Sugar Land" },
  { slug: "phoenix-az", city: "Phoenix", state: "Arizona", stateCode: "AZ", population: 1608139, tier: "major", region: "Southwest", latitude: 33.4484, longitude: -112.0740, metro: "Phoenix-Mesa-Chandler" },
  { slug: "philadelphia-pa", city: "Philadelphia", state: "Pennsylvania", stateCode: "PA", population: 1603797, tier: "major", region: "Northeast", latitude: 39.9526, longitude: -75.1652, metro: "Philadelphia-Camden-Wilmington" },
  { slug: "san-antonio-tx", city: "San Antonio", state: "Texas", stateCode: "TX", population: 1547253, tier: "major", region: "Southwest", latitude: 29.4241, longitude: -98.4936, metro: "San Antonio-New Braunfels" },
  { slug: "san-diego-ca", city: "San Diego", state: "California", stateCode: "CA", population: 1386932, tier: "major", region: "West", latitude: 32.7157, longitude: -117.1611, metro: "San Diego-Carlsbad" },
  { slug: "dallas-tx", city: "Dallas", state: "Texas", stateCode: "TX", population: 1304379, tier: "major", region: "Southwest", latitude: 32.7767, longitude: -96.7970, metro: "Dallas-Fort Worth-Arlington" },
  { slug: "san-jose-ca", city: "San Jose", state: "California", stateCode: "CA", population: 1013240, tier: "major", region: "West", latitude: 37.3382, longitude: -121.8863, metro: "San Jose-Sunnyvale-Santa Clara" },
  { slug: "austin-tx", city: "Austin", state: "Texas", stateCode: "TX", population: 978908, tier: "major", region: "Southwest", latitude: 30.2672, longitude: -97.7431, metro: "Austin-Round Rock-Georgetown" },
  { slug: "jacksonville-fl", city: "Jacksonville", state: "Florida", stateCode: "FL", population: 949611, tier: "major", region: "Southeast", latitude: 30.3322, longitude: -81.6557, metro: "Jacksonville" },
  { slug: "fort-worth-tx", city: "Fort Worth", state: "Texas", stateCode: "TX", population: 918915, tier: "major", region: "Southwest", latitude: 32.7555, longitude: -97.3308, metro: "Dallas-Fort Worth-Arlington" },
  { slug: "columbus-oh", city: "Columbus", state: "Ohio", stateCode: "OH", population: 905748, tier: "major", region: "Midwest", latitude: 39.9612, longitude: -82.9988, metro: "Columbus" },
  { slug: "charlotte-nc", city: "Charlotte", state: "North Carolina", stateCode: "NC", population: 874579, tier: "major", region: "Southeast", latitude: 35.2271, longitude: -80.8431, metro: "Charlotte-Concord-Gastonia" },
  { slug: "san-francisco-ca", city: "San Francisco", state: "California", stateCode: "CA", population: 873965, tier: "major", region: "West", latitude: 37.7749, longitude: -122.4194, metro: "San Francisco-Oakland-Berkeley" },
  { slug: "indianapolis-in", city: "Indianapolis", state: "Indiana", stateCode: "IN", population: 867125, tier: "major", region: "Midwest", latitude: 39.7684, longitude: -86.1581, metro: "Indianapolis-Carmel-Anderson" },
  { slug: "seattle-wa", city: "Seattle", state: "Washington", stateCode: "WA", population: 737015, tier: "major", region: "West", latitude: 47.6062, longitude: -122.3321, metro: "Seattle-Tacoma-Bellevue" },
  { slug: "denver-co", city: "Denver", state: "Colorado", stateCode: "CO", population: 715522, tier: "major", region: "West", latitude: 39.7392, longitude: -104.9903, metro: "Denver-Aurora-Lakewood" },
  { slug: "washington-dc", city: "Washington", state: "District of Columbia", stateCode: "DC", population: 689545, tier: "major", region: "Northeast", latitude: 38.9072, longitude: -77.0369, metro: "Washington-Arlington-Alexandria" },
  { slug: "boston-ma", city: "Boston", state: "Massachusetts", stateCode: "MA", population: 675647, tier: "major", region: "Northeast", latitude: 42.3601, longitude: -71.0589, metro: "Boston-Cambridge-Newton" },
  { slug: "el-paso-tx", city: "El Paso", state: "Texas", stateCode: "TX", population: 678815, tier: "major", region: "Southwest", latitude: 31.7619, longitude: -106.4850, metro: "El Paso" },
  { slug: "nashville-tn", city: "Nashville", state: "Tennessee", stateCode: "TN", population: 689447, tier: "major", region: "Southeast", latitude: 36.1627, longitude: -86.7816, metro: "Nashville-Davidson-Murfreesboro" },
  { slug: "detroit-mi", city: "Detroit", state: "Michigan", stateCode: "MI", population: 639111, tier: "major", region: "Midwest", latitude: 42.3314, longitude: -83.0458, metro: "Detroit-Warren-Dearborn" },
  { slug: "oklahoma-city-ok", city: "Oklahoma City", state: "Oklahoma", stateCode: "OK", population: 687725, tier: "major", region: "Southwest", latitude: 35.4676, longitude: -97.5164, metro: "Oklahoma City" },
  { slug: "portland-or", city: "Portland", state: "Oregon", stateCode: "OR", population: 652503, tier: "major", region: "West", latitude: 45.5152, longitude: -122.6784, metro: "Portland-Vancouver-Hillsboro" },
  { slug: "las-vegas-nv", city: "Las Vegas", state: "Nevada", stateCode: "NV", population: 641903, tier: "major", region: "West", latitude: 36.1699, longitude: -115.1398, metro: "Las Vegas-Henderson-Paradise" },
  { slug: "memphis-tn", city: "Memphis", state: "Tennessee", stateCode: "TN", population: 633104, tier: "major", region: "Southeast", latitude: 35.1495, longitude: -90.0490, metro: "Memphis" },
  { slug: "louisville-ky", city: "Louisville", state: "Kentucky", stateCode: "KY", population: 617638, tier: "major", region: "Southeast", latitude: 38.2527, longitude: -85.7585, metro: "Louisville-Jefferson County" },
  { slug: "baltimore-md", city: "Baltimore", state: "Maryland", stateCode: "MD", population: 585708, tier: "major", region: "Northeast", latitude: 39.2904, longitude: -76.6122, metro: "Baltimore-Columbia-Towson" },
  { slug: "milwaukee-wi", city: "Milwaukee", state: "Wisconsin", stateCode: "WI", population: 577222, tier: "major", region: "Midwest", latitude: 43.0389, longitude: -87.9065, metro: "Milwaukee-Waukesha" },
  { slug: "albuquerque-nm", city: "Albuquerque", state: "New Mexico", stateCode: "NM", population: 564559, tier: "major", region: "Southwest", latitude: 35.0844, longitude: -106.6504, metro: "Albuquerque" },
  { slug: "tucson-az", city: "Tucson", state: "Arizona", stateCode: "AZ", population: 542629, tier: "major", region: "Southwest", latitude: 32.2226, longitude: -110.9747, metro: "Tucson" },
  { slug: "fresno-ca", city: "Fresno", state: "California", stateCode: "CA", population: 542107, tier: "major", region: "West", latitude: 36.7378, longitude: -119.7871, metro: "Fresno" },
  { slug: "atlanta-ga", city: "Atlanta", state: "Georgia", stateCode: "GA", population: 498715, tier: "major", region: "Southeast", latitude: 33.7490, longitude: -84.3880, metro: "Atlanta-Sandy Springs-Alpharetta" },
];

// Tier 2: Large Cities (Pop 200K-500K) - 85 cities
const largeCities: USCity[] = [
  { slug: "miami-fl", city: "Miami", state: "Florida", stateCode: "FL", population: 449514, tier: "large", region: "Southeast", latitude: 25.7617, longitude: -80.1918, metro: "Miami-Fort Lauderdale-Pompano Beach" },
  { slug: "sacramento-ca", city: "Sacramento", state: "California", stateCode: "CA", population: 524943, tier: "large", region: "West", latitude: 38.5816, longitude: -121.4944, metro: "Sacramento-Roseville-Folsom" },
  { slug: "mesa-az", city: "Mesa", state: "Arizona", stateCode: "AZ", population: 504258, tier: "large", region: "Southwest", latitude: 33.4152, longitude: -111.8315, metro: "Phoenix-Mesa-Chandler" },
  { slug: "kansas-city-mo", city: "Kansas City", state: "Missouri", stateCode: "MO", population: 508090, tier: "large", region: "Midwest", latitude: 39.0997, longitude: -94.5786, metro: "Kansas City" },
  { slug: "colorado-springs-co", city: "Colorado Springs", state: "Colorado", stateCode: "CO", population: 478961, tier: "large", region: "West", latitude: 38.8339, longitude: -104.8214, metro: "Colorado Springs" },
  { slug: "virginia-beach-va", city: "Virginia Beach", state: "Virginia", stateCode: "VA", population: 459470, tier: "large", region: "Southeast", latitude: 36.8529, longitude: -75.9780, metro: "Virginia Beach-Norfolk-Newport News" },
  { slug: "raleigh-nc", city: "Raleigh", state: "North Carolina", stateCode: "NC", population: 467665, tier: "large", region: "Southeast", latitude: 35.7796, longitude: -78.6382, metro: "Raleigh-Cary" },
  { slug: "omaha-ne", city: "Omaha", state: "Nebraska", stateCode: "NE", population: 485246, tier: "large", region: "Midwest", latitude: 41.2565, longitude: -95.9345, metro: "Omaha-Council Bluffs" },
  { slug: "long-beach-ca", city: "Long Beach", state: "California", stateCode: "CA", population: 466742, tier: "large", region: "West", latitude: 33.7701, longitude: -118.1937, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "oakland-ca", city: "Oakland", state: "California", stateCode: "CA", population: 433031, tier: "large", region: "West", latitude: 37.8044, longitude: -122.2712, metro: "San Francisco-Oakland-Berkeley" },
  { slug: "minneapolis-mn", city: "Minneapolis", state: "Minnesota", stateCode: "MN", population: 429954, tier: "large", region: "Midwest", latitude: 44.9778, longitude: -93.2650, metro: "Minneapolis-St. Paul-Bloomington" },
  { slug: "tampa-fl", city: "Tampa", state: "Florida", stateCode: "FL", population: 387050, tier: "large", region: "Southeast", latitude: 27.9506, longitude: -82.4572, metro: "Tampa-St. Petersburg-Clearwater" },
  { slug: "tulsa-ok", city: "Tulsa", state: "Oklahoma", stateCode: "OK", population: 413066, tier: "large", region: "Southwest", latitude: 36.1540, longitude: -95.9928, metro: "Tulsa" },
  { slug: "arlington-tx", city: "Arlington", state: "Texas", stateCode: "TX", population: 394266, tier: "large", region: "Southwest", latitude: 32.7357, longitude: -97.1081, metro: "Dallas-Fort Worth-Arlington" },
  { slug: "new-orleans-la", city: "New Orleans", state: "Louisiana", stateCode: "LA", population: 383997, tier: "large", region: "Southeast", latitude: 29.9511, longitude: -90.0715, metro: "New Orleans-Metairie" },
  { slug: "wichita-ks", city: "Wichita", state: "Kansas", stateCode: "KS", population: 397532, tier: "large", region: "Midwest", latitude: 37.6872, longitude: -97.3301, metro: "Wichita" },
  { slug: "bakersfield-ca", city: "Bakersfield", state: "California", stateCode: "CA", population: 403455, tier: "large", region: "West", latitude: 35.3733, longitude: -119.0187, metro: "Bakersfield" },
  { slug: "cleveland-oh", city: "Cleveland", state: "Ohio", stateCode: "OH", population: 372624, tier: "large", region: "Midwest", latitude: 41.4993, longitude: -81.6944, metro: "Cleveland-Elyria" },
  { slug: "aurora-co", city: "Aurora", state: "Colorado", stateCode: "CO", population: 386261, tier: "large", region: "West", latitude: 39.7294, longitude: -104.8319, metro: "Denver-Aurora-Lakewood" },
  { slug: "anaheim-ca", city: "Anaheim", state: "California", stateCode: "CA", population: 350365, tier: "large", region: "West", latitude: 33.8366, longitude: -117.9143, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "honolulu-hi", city: "Honolulu", state: "Hawaii", stateCode: "HI", population: 350964, tier: "large", region: "West", latitude: 21.3069, longitude: -157.8583, metro: "Urban Honolulu" },
  { slug: "santa-ana-ca", city: "Santa Ana", state: "California", stateCode: "CA", population: 310227, tier: "large", region: "West", latitude: 33.7455, longitude: -117.8677, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "riverside-ca", city: "Riverside", state: "California", stateCode: "CA", population: 314998, tier: "large", region: "West", latitude: 33.9533, longitude: -117.3962, metro: "Riverside-San Bernardino-Ontario" },
  { slug: "corpus-christi-tx", city: "Corpus Christi", state: "Texas", stateCode: "TX", population: 317863, tier: "large", region: "Southwest", latitude: 27.8006, longitude: -97.3964, metro: "Corpus Christi" },
  { slug: "lexington-ky", city: "Lexington", state: "Kentucky", stateCode: "KY", population: 322570, tier: "large", region: "Southeast", latitude: 38.0406, longitude: -84.5037, metro: "Lexington-Fayette" },
  { slug: "henderson-nv", city: "Henderson", state: "Nevada", stateCode: "NV", population: 320189, tier: "large", region: "West", latitude: 36.0395, longitude: -114.9817, metro: "Las Vegas-Henderson-Paradise" },
  { slug: "stockton-ca", city: "Stockton", state: "California", stateCode: "CA", population: 320804, tier: "large", region: "West", latitude: 37.9577, longitude: -121.2908, metro: "Stockton" },
  { slug: "st-paul-mn", city: "St. Paul", state: "Minnesota", stateCode: "MN", population: 311527, tier: "large", region: "Midwest", latitude: 44.9537, longitude: -93.0900, metro: "Minneapolis-St. Paul-Bloomington" },
  { slug: "cincinnati-oh", city: "Cincinnati", state: "Ohio", stateCode: "OH", population: 309317, tier: "large", region: "Midwest", latitude: 39.1031, longitude: -84.5120, metro: "Cincinnati" },
  { slug: "st-louis-mo", city: "St. Louis", state: "Missouri", stateCode: "MO", population: 301578, tier: "large", region: "Midwest", latitude: 38.6270, longitude: -90.1994, metro: "St. Louis" },
  { slug: "pittsburgh-pa", city: "Pittsburgh", state: "Pennsylvania", stateCode: "PA", population: 302971, tier: "large", region: "Northeast", latitude: 40.4406, longitude: -79.9959, metro: "Pittsburgh" },
  { slug: "greensboro-nc", city: "Greensboro", state: "North Carolina", stateCode: "NC", population: 299035, tier: "large", region: "Southeast", latitude: 36.0726, longitude: -79.7920, metro: "Greensboro-High Point" },
  { slug: "anchorage-ak", city: "Anchorage", state: "Alaska", stateCode: "AK", population: 291247, tier: "large", region: "West", latitude: 61.2181, longitude: -149.9003, metro: "Anchorage" },
  { slug: "plano-tx", city: "Plano", state: "Texas", stateCode: "TX", population: 285494, tier: "large", region: "Southwest", latitude: 33.0198, longitude: -96.6989, metro: "Dallas-Fort Worth-Arlington" },
  { slug: "lincoln-ne", city: "Lincoln", state: "Nebraska", stateCode: "NE", population: 291082, tier: "large", region: "Midwest", latitude: 40.8258, longitude: -96.6852, metro: "Lincoln" },
  { slug: "orlando-fl", city: "Orlando", state: "Florida", stateCode: "FL", population: 307573, tier: "large", region: "Southeast", latitude: 28.5383, longitude: -81.3792, metro: "Orlando-Kissimmee-Sanford" },
  { slug: "irvine-ca", city: "Irvine", state: "California", stateCode: "CA", population: 307670, tier: "large", region: "West", latitude: 33.6839, longitude: -117.7947, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "newark-nj", city: "Newark", state: "New Jersey", stateCode: "NJ", population: 311549, tier: "large", region: "Northeast", latitude: 40.7357, longitude: -74.1724, metro: "New York-Newark-Jersey City" },
  { slug: "durham-nc", city: "Durham", state: "North Carolina", stateCode: "NC", population: 283506, tier: "large", region: "Southeast", latitude: 35.9940, longitude: -78.8986, metro: "Durham-Chapel Hill" },
  { slug: "chula-vista-ca", city: "Chula Vista", state: "California", stateCode: "CA", population: 275487, tier: "large", region: "West", latitude: 32.6401, longitude: -117.0842, metro: "San Diego-Carlsbad" },
  { slug: "toledo-oh", city: "Toledo", state: "Ohio", stateCode: "OH", population: 270871, tier: "large", region: "Midwest", latitude: 41.6528, longitude: -83.5379, metro: "Toledo" },
  { slug: "fort-wayne-in", city: "Fort Wayne", state: "Indiana", stateCode: "IN", population: 270402, tier: "large", region: "Midwest", latitude: 41.0793, longitude: -85.1394, metro: "Fort Wayne" },
  { slug: "st-petersburg-fl", city: "St. Petersburg", state: "Florida", stateCode: "FL", population: 258308, tier: "large", region: "Southeast", latitude: 27.7676, longitude: -82.6403, metro: "Tampa-St. Petersburg-Clearwater" },
  { slug: "laredo-tx", city: "Laredo", state: "Texas", stateCode: "TX", population: 255473, tier: "large", region: "Southwest", latitude: 27.5306, longitude: -99.4803, metro: "Laredo" },
  { slug: "jersey-city-nj", city: "Jersey City", state: "New Jersey", stateCode: "NJ", population: 292449, tier: "large", region: "Northeast", latitude: 40.7178, longitude: -74.0431, metro: "New York-Newark-Jersey City" },
  { slug: "chandler-az", city: "Chandler", state: "Arizona", stateCode: "AZ", population: 275987, tier: "large", region: "Southwest", latitude: 33.3062, longitude: -111.8413, metro: "Phoenix-Mesa-Chandler" },
  { slug: "buffalo-ny", city: "Buffalo", state: "New York", stateCode: "NY", population: 278349, tier: "large", region: "Northeast", latitude: 42.8864, longitude: -78.8784, metro: "Buffalo-Cheektowaga" },
  { slug: "madison-wi", city: "Madison", state: "Wisconsin", stateCode: "WI", population: 269840, tier: "large", region: "Midwest", latitude: 43.0731, longitude: -89.4012, metro: "Madison" },
  { slug: "lubbock-tx", city: "Lubbock", state: "Texas", stateCode: "TX", population: 264778, tier: "large", region: "Southwest", latitude: 33.5779, longitude: -101.8552, metro: "Lubbock" },
  { slug: "scottsdale-az", city: "Scottsdale", state: "Arizona", stateCode: "AZ", population: 241361, tier: "large", region: "Southwest", latitude: 33.4942, longitude: -111.9261, metro: "Phoenix-Mesa-Chandler" },
  { slug: "reno-nv", city: "Reno", state: "Nevada", stateCode: "NV", population: 264165, tier: "large", region: "West", latitude: 39.5296, longitude: -119.8138, metro: "Reno" },
  { slug: "glendale-az", city: "Glendale", state: "Arizona", stateCode: "AZ", population: 248325, tier: "large", region: "Southwest", latitude: 33.5387, longitude: -112.1860, metro: "Phoenix-Mesa-Chandler" },
  { slug: "gilbert-az", city: "Gilbert", state: "Arizona", stateCode: "AZ", population: 267918, tier: "large", region: "Southwest", latitude: 33.3528, longitude: -111.7890, metro: "Phoenix-Mesa-Chandler" },
  { slug: "winston-salem-nc", city: "Winston-Salem", state: "North Carolina", stateCode: "NC", population: 249545, tier: "large", region: "Southeast", latitude: 36.0999, longitude: -80.2442, metro: "Winston-Salem" },
  { slug: "north-las-vegas-nv", city: "North Las Vegas", state: "Nevada", stateCode: "NV", population: 262527, tier: "large", region: "West", latitude: 36.1989, longitude: -115.1175, metro: "Las Vegas-Henderson-Paradise" },
  { slug: "norfolk-va", city: "Norfolk", state: "Virginia", stateCode: "VA", population: 238005, tier: "large", region: "Southeast", latitude: 36.8508, longitude: -76.2859, metro: "Virginia Beach-Norfolk-Newport News" },
  { slug: "chesapeake-va", city: "Chesapeake", state: "Virginia", stateCode: "VA", population: 249422, tier: "large", region: "Southeast", latitude: 36.7682, longitude: -76.2875, metro: "Virginia Beach-Norfolk-Newport News" },
  { slug: "irving-tx", city: "Irving", state: "Texas", stateCode: "TX", population: 256684, tier: "large", region: "Southwest", latitude: 32.8140, longitude: -96.9489, metro: "Dallas-Fort Worth-Arlington" },
  { slug: "fremont-ca", city: "Fremont", state: "California", stateCode: "CA", population: 230504, tier: "large", region: "West", latitude: 37.5485, longitude: -121.9886, metro: "San Francisco-Oakland-Berkeley" },
  { slug: "garland-tx", city: "Garland", state: "Texas", stateCode: "TX", population: 246018, tier: "large", region: "Southwest", latitude: 32.9126, longitude: -96.6389, metro: "Dallas-Fort Worth-Arlington" },
  { slug: "hialeah-fl", city: "Hialeah", state: "Florida", stateCode: "FL", population: 223109, tier: "large", region: "Southeast", latitude: 25.8576, longitude: -80.2781, metro: "Miami-Fort Lauderdale-Pompano Beach" },
  { slug: "richmond-va", city: "Richmond", state: "Virginia", stateCode: "VA", population: 226610, tier: "large", region: "Southeast", latitude: 37.5407, longitude: -77.4360, metro: "Richmond" },
  { slug: "boise-id", city: "Boise", state: "Idaho", stateCode: "ID", population: 235684, tier: "large", region: "West", latitude: 43.6150, longitude: -116.2023, metro: "Boise City" },
  { slug: "spokane-wa", city: "Spokane", state: "Washington", stateCode: "WA", population: 228989, tier: "large", region: "West", latitude: 47.6588, longitude: -117.4260, metro: "Spokane-Spokane Valley" },
  { slug: "baton-rouge-la", city: "Baton Rouge", state: "Louisiana", stateCode: "LA", population: 227470, tier: "large", region: "Southeast", latitude: 30.4515, longitude: -91.1871, metro: "Baton Rouge" },
  { slug: "tacoma-wa", city: "Tacoma", state: "Washington", stateCode: "WA", population: 219346, tier: "large", region: "West", latitude: 47.2529, longitude: -122.4443, metro: "Seattle-Tacoma-Bellevue" },
  { slug: "san-bernardino-ca", city: "San Bernardino", state: "California", stateCode: "CA", population: 222101, tier: "large", region: "West", latitude: 34.1083, longitude: -117.2898, metro: "Riverside-San Bernardino-Ontario" },
  { slug: "modesto-ca", city: "Modesto", state: "California", stateCode: "CA", population: 218464, tier: "large", region: "West", latitude: 37.6390, longitude: -120.9969, metro: "Modesto" },
  { slug: "fontana-ca", city: "Fontana", state: "California", stateCode: "CA", population: 214547, tier: "large", region: "West", latitude: 34.0922, longitude: -117.4350, metro: "Riverside-San Bernardino-Ontario" },
  { slug: "des-moines-ia", city: "Des Moines", state: "Iowa", stateCode: "IA", population: 214133, tier: "large", region: "Midwest", latitude: 41.5868, longitude: -93.6250, metro: "Des Moines-West Des Moines" },
  { slug: "moreno-valley-ca", city: "Moreno Valley", state: "California", stateCode: "CA", population: 212976, tier: "large", region: "West", latitude: 33.9425, longitude: -117.2297, metro: "Riverside-San Bernardino-Ontario" },
  { slug: "fayetteville-nc", city: "Fayetteville", state: "North Carolina", stateCode: "NC", population: 208501, tier: "large", region: "Southeast", latitude: 35.0527, longitude: -78.8784, metro: "Fayetteville" },
  { slug: "birmingham-al", city: "Birmingham", state: "Alabama", stateCode: "AL", population: 200733, tier: "large", region: "Southeast", latitude: 33.5207, longitude: -86.8025, metro: "Birmingham-Hoover" },
  { slug: "santa-clarita-ca", city: "Santa Clarita", state: "California", stateCode: "CA", population: 228673, tier: "large", region: "West", latitude: 34.3917, longitude: -118.5426, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "glendale-ca", city: "Glendale", state: "California", stateCode: "CA", population: 196543, tier: "large", region: "West", latitude: 34.1425, longitude: -118.2551, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "huntington-beach-ca", city: "Huntington Beach", state: "California", stateCode: "CA", population: 198711, tier: "large", region: "West", latitude: 33.6595, longitude: -117.9988, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "grand-rapids-mi", city: "Grand Rapids", state: "Michigan", stateCode: "MI", population: 198917, tier: "large", region: "Midwest", latitude: 42.9634, longitude: -85.6681, metro: "Grand Rapids-Kentwood" },
  { slug: "salt-lake-city-ut", city: "Salt Lake City", state: "Utah", stateCode: "UT", population: 199723, tier: "large", region: "West", latitude: 40.7608, longitude: -111.8910, metro: "Salt Lake City" },
  { slug: "rochester-ny", city: "Rochester", state: "New York", stateCode: "NY", population: 211328, tier: "large", region: "Northeast", latitude: 43.1566, longitude: -77.6088, metro: "Rochester" },
  { slug: "yonkers-ny", city: "Yonkers", state: "New York", stateCode: "NY", population: 211569, tier: "large", region: "Northeast", latitude: 40.9312, longitude: -73.8987, metro: "New York-Newark-Jersey City" },
  { slug: "amarillo-tx", city: "Amarillo", state: "Texas", stateCode: "TX", population: 200393, tier: "large", region: "Southwest", latitude: 35.2220, longitude: -101.8313, metro: "Amarillo" },
  { slug: "huntsville-al", city: "Huntsville", state: "Alabama", stateCode: "AL", population: 215006, tier: "large", region: "Southeast", latitude: 34.7304, longitude: -86.5861, metro: "Huntsville" },
  { slug: "montgomery-al", city: "Montgomery", state: "Alabama", stateCode: "AL", population: 200603, tier: "large", region: "Southeast", latitude: 32.3792, longitude: -86.3077, metro: "Montgomery" },
];

// Tier 3: Medium Cities (Pop 100K-200K) - 130 cities
const mediumCities: USCity[] = [
  { slug: "little-rock-ar", city: "Little Rock", state: "Arkansas", stateCode: "AR", population: 202591, tier: "medium", region: "Southeast", latitude: 34.7465, longitude: -92.2896, metro: "Little Rock-North Little Rock-Conway" },
  { slug: "augusta-ga", city: "Augusta", state: "Georgia", stateCode: "GA", population: 202081, tier: "medium", region: "Southeast", latitude: 33.4735, longitude: -82.0105, metro: "Augusta-Richmond County" },
  { slug: "akron-oh", city: "Akron", state: "Ohio", stateCode: "OH", population: 190469, tier: "medium", region: "Midwest", latitude: 41.0814, longitude: -81.5190, metro: "Akron" },
  { slug: "knoxville-tn", city: "Knoxville", state: "Tennessee", stateCode: "TN", population: 190740, tier: "medium", region: "Southeast", latitude: 35.9606, longitude: -83.9207, metro: "Knoxville" },
  { slug: "shreveport-la", city: "Shreveport", state: "Louisiana", stateCode: "LA", population: 187593, tier: "medium", region: "Southeast", latitude: 32.5252, longitude: -93.7502, metro: "Shreveport-Bossier City" },
  { slug: "mobile-al", city: "Mobile", state: "Alabama", stateCode: "AL", population: 187041, tier: "medium", region: "Southeast", latitude: 30.6954, longitude: -88.0399, metro: "Mobile" },
  { slug: "grand-prairie-tx", city: "Grand Prairie", state: "Texas", stateCode: "TX", population: 196100, tier: "medium", region: "Southwest", latitude: 32.7459, longitude: -96.9978, metro: "Dallas-Fort Worth-Arlington" },
  { slug: "overland-park-ks", city: "Overland Park", state: "Kansas", stateCode: "KS", population: 197238, tier: "medium", region: "Midwest", latitude: 38.9822, longitude: -94.6708, metro: "Kansas City" },
  { slug: "tallahassee-fl", city: "Tallahassee", state: "Florida", stateCode: "FL", population: 196169, tier: "medium", region: "Southeast", latitude: 30.4383, longitude: -84.2807, metro: "Tallahassee" },
  { slug: "cape-coral-fl", city: "Cape Coral", state: "Florida", stateCode: "FL", population: 194016, tier: "medium", region: "Southeast", latitude: 26.5629, longitude: -81.9495, metro: "Cape Coral-Fort Myers" },
  { slug: "worcester-ma", city: "Worcester", state: "Massachusetts", stateCode: "MA", population: 206518, tier: "medium", region: "Northeast", latitude: 42.2626, longitude: -71.8023, metro: "Worcester" },
  { slug: "ontario-ca", city: "Ontario", state: "California", stateCode: "CA", population: 175265, tier: "medium", region: "West", latitude: 34.0633, longitude: -117.6509, metro: "Riverside-San Bernardino-Ontario" },
  { slug: "providence-ri", city: "Providence", state: "Rhode Island", stateCode: "RI", population: 189692, tier: "medium", region: "Northeast", latitude: 41.8240, longitude: -71.4128, metro: "Providence-Warwick" },
  { slug: "brownsville-tx", city: "Brownsville", state: "Texas", stateCode: "TX", population: 186738, tier: "medium", region: "Southwest", latitude: 25.9017, longitude: -97.4975, metro: "Brownsville-Harlingen" },
  { slug: "santa-rosa-ca", city: "Santa Rosa", state: "California", stateCode: "CA", population: 178127, tier: "medium", region: "West", latitude: 38.4404, longitude: -122.7141, metro: "Santa Rosa-Petaluma" },
  { slug: "port-st-lucie-fl", city: "Port St. Lucie", state: "Florida", stateCode: "FL", population: 204851, tier: "medium", region: "Southeast", latitude: 27.2730, longitude: -80.3582, metro: "Port St. Lucie" },
  { slug: "tempe-az", city: "Tempe", state: "Arizona", stateCode: "AZ", population: 180587, tier: "medium", region: "Southwest", latitude: 33.4255, longitude: -111.9400, metro: "Phoenix-Mesa-Chandler" },
  { slug: "vancouver-wa", city: "Vancouver", state: "Washington", stateCode: "WA", population: 190915, tier: "medium", region: "West", latitude: 45.6387, longitude: -122.6615, metro: "Portland-Vancouver-Hillsboro" },
  { slug: "chattanooga-tn", city: "Chattanooga", state: "Tennessee", stateCode: "TN", population: 181099, tier: "medium", region: "Southeast", latitude: 35.0456, longitude: -85.3097, metro: "Chattanooga" },
  { slug: "eugene-or", city: "Eugene", state: "Oregon", stateCode: "OR", population: 176654, tier: "medium", region: "West", latitude: 44.0521, longitude: -123.0868, metro: "Eugene-Springfield" },
  { slug: "springfield-mo", city: "Springfield", state: "Missouri", stateCode: "MO", population: 169176, tier: "medium", region: "Midwest", latitude: 37.2090, longitude: -93.2923, metro: "Springfield" },
  { slug: "pembroke-pines-fl", city: "Pembroke Pines", state: "Florida", stateCode: "FL", population: 171178, tier: "medium", region: "Southeast", latitude: 26.0073, longitude: -80.2241, metro: "Miami-Fort Lauderdale-Pompano Beach" },
  { slug: "salem-or", city: "Salem", state: "Oregon", stateCode: "OR", population: 175535, tier: "medium", region: "West", latitude: 44.9429, longitude: -123.0351, metro: "Salem" },
  { slug: "peoria-az", city: "Peoria", state: "Arizona", stateCode: "AZ", population: 190985, tier: "medium", region: "Southwest", latitude: 33.5806, longitude: -112.2374, metro: "Phoenix-Mesa-Chandler" },
  { slug: "sioux-falls-sd", city: "Sioux Falls", state: "South Dakota", stateCode: "SD", population: 192517, tier: "medium", region: "Midwest", latitude: 43.5460, longitude: -96.7313, metro: "Sioux Falls" },
  { slug: "oceanside-ca", city: "Oceanside", state: "California", stateCode: "CA", population: 176193, tier: "medium", region: "West", latitude: 33.1959, longitude: -117.3795, metro: "San Diego-Carlsbad" },
  { slug: "elk-grove-ca", city: "Elk Grove", state: "California", stateCode: "CA", population: 176124, tier: "medium", region: "West", latitude: 38.4088, longitude: -121.3716, metro: "Sacramento-Roseville-Folsom" },
  { slug: "fort-collins-co", city: "Fort Collins", state: "Colorado", stateCode: "CO", population: 169810, tier: "medium", region: "West", latitude: 40.5853, longitude: -105.0844, metro: "Fort Collins" },
  { slug: "corona-ca", city: "Corona", state: "California", stateCode: "CA", population: 157136, tier: "medium", region: "West", latitude: 33.8753, longitude: -117.5664, metro: "Riverside-San Bernardino-Ontario" },
  { slug: "cary-nc", city: "Cary", state: "North Carolina", stateCode: "NC", population: 174721, tier: "medium", region: "Southeast", latitude: 35.7915, longitude: -78.7811, metro: "Raleigh-Cary" },
  { slug: "springfield-ma", city: "Springfield", state: "Massachusetts", stateCode: "MA", population: 155929, tier: "medium", region: "Northeast", latitude: 42.1015, longitude: -72.5898, metro: "Springfield" },
  { slug: "fort-lauderdale-fl", city: "Fort Lauderdale", state: "Florida", stateCode: "FL", population: 182760, tier: "medium", region: "Southeast", latitude: 26.1224, longitude: -80.1373, metro: "Miami-Fort Lauderdale-Pompano Beach" },
  { slug: "carlsbad-ca", city: "Carlsbad", state: "California", stateCode: "CA", population: 114746, tier: "medium", region: "West", latitude: 33.1581, longitude: -117.3506, metro: "San Diego-Carlsbad" },
  { slug: "palmdale-ca", city: "Palmdale", state: "California", stateCode: "CA", population: 169450, tier: "medium", region: "West", latitude: 34.5794, longitude: -118.1165, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "mckinney-tx", city: "McKinney", state: "Texas", stateCode: "TX", population: 195308, tier: "medium", region: "Southwest", latitude: 33.1972, longitude: -96.6397, metro: "Dallas-Fort Worth-Arlington" },
  { slug: "frisco-tx", city: "Frisco", state: "Texas", stateCode: "TX", population: 200509, tier: "medium", region: "Southwest", latitude: 33.1507, longitude: -96.8236, metro: "Dallas-Fort Worth-Arlington" },
  { slug: "clarksville-tn", city: "Clarksville", state: "Tennessee", stateCode: "TN", population: 166722, tier: "medium", region: "Southeast", latitude: 36.5298, longitude: -87.3595, metro: "Clarksville" },
  { slug: "joliet-il", city: "Joliet", state: "Illinois", stateCode: "IL", population: 150362, tier: "medium", region: "Midwest", latitude: 41.5250, longitude: -88.0817, metro: "Chicago-Naperville-Elgin" },
  { slug: "visalia-ca", city: "Visalia", state: "California", stateCode: "CA", population: 141384, tier: "medium", region: "West", latitude: 36.3302, longitude: -119.2921, metro: "Visalia" },
  { slug: "miramar-fl", city: "Miramar", state: "Florida", stateCode: "FL", population: 134068, tier: "medium", region: "Southeast", latitude: 25.9860, longitude: -80.3357, metro: "Miami-Fort Lauderdale-Pompano Beach" },
  { slug: "paterson-nj", city: "Paterson", state: "New Jersey", stateCode: "NJ", population: 159732, tier: "medium", region: "Northeast", latitude: 40.9168, longitude: -74.1718, metro: "New York-Newark-Jersey City" },
  { slug: "savannah-ga", city: "Savannah", state: "Georgia", stateCode: "GA", population: 147780, tier: "medium", region: "Southeast", latitude: 32.0809, longitude: -81.0912, metro: "Savannah" },
  { slug: "olathe-ks", city: "Olathe", state: "Kansas", stateCode: "KS", population: 141290, tier: "medium", region: "Midwest", latitude: 38.8814, longitude: -94.8191, metro: "Kansas City" },
  { slug: "pasadena-tx", city: "Pasadena", state: "Texas", stateCode: "TX", population: 151950, tier: "medium", region: "Southwest", latitude: 29.6911, longitude: -95.2091, metro: "Houston-The Woodlands-Sugar Land" },
  { slug: "bridgeport-ct", city: "Bridgeport", state: "Connecticut", stateCode: "CT", population: 148654, tier: "medium", region: "Northeast", latitude: 41.1865, longitude: -73.1952, metro: "Bridgeport-Stamford-Norwalk" },
  { slug: "hayward-ca", city: "Hayward", state: "California", stateCode: "CA", population: 162954, tier: "medium", region: "West", latitude: 37.6688, longitude: -122.0808, metro: "San Francisco-Oakland-Berkeley" },
  { slug: "pomona-ca", city: "Pomona", state: "California", stateCode: "CA", population: 151348, tier: "medium", region: "West", latitude: 34.0551, longitude: -117.7500, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "escondido-ca", city: "Escondido", state: "California", stateCode: "CA", population: 151038, tier: "medium", region: "West", latitude: 33.1192, longitude: -117.0864, metro: "San Diego-Carlsbad" },
  { slug: "sunnyvale-ca", city: "Sunnyvale", state: "California", stateCode: "CA", population: 155805, tier: "medium", region: "West", latitude: 37.3688, longitude: -122.0363, metro: "San Jose-Sunnyvale-Santa Clara" },
  { slug: "alexandria-va", city: "Alexandria", state: "Virginia", stateCode: "VA", population: 159467, tier: "medium", region: "Northeast", latitude: 38.8048, longitude: -77.0469, metro: "Washington-Arlington-Alexandria" },
  { slug: "lakewood-co", city: "Lakewood", state: "Colorado", stateCode: "CO", population: 155984, tier: "medium", region: "West", latitude: 39.7047, longitude: -105.0814, metro: "Denver-Aurora-Lakewood" },
  { slug: "killeen-tx", city: "Killeen", state: "Texas", stateCode: "TX", population: 153095, tier: "medium", region: "Southwest", latitude: 31.1171, longitude: -97.7278, metro: "Killeen-Temple" },
  { slug: "salinas-ca", city: "Salinas", state: "California", stateCode: "CA", population: 163542, tier: "medium", region: "West", latitude: 36.6777, longitude: -121.6555, metro: "Salinas" },
  { slug: "hollywood-fl", city: "Hollywood", state: "Florida", stateCode: "FL", population: 153067, tier: "medium", region: "Southeast", latitude: 26.0112, longitude: -80.1495, metro: "Miami-Fort Lauderdale-Pompano Beach" },
  { slug: "murfreesboro-tn", city: "Murfreesboro", state: "Tennessee", stateCode: "TN", population: 152769, tier: "medium", region: "Southeast", latitude: 35.8456, longitude: -86.3903, metro: "Nashville-Davidson-Murfreesboro" },
  { slug: "pasadena-ca", city: "Pasadena", state: "California", stateCode: "CA", population: 138699, tier: "medium", region: "West", latitude: 34.1478, longitude: -118.1445, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "mesquite-tx", city: "Mesquite", state: "Texas", stateCode: "TX", population: 150108, tier: "medium", region: "Southwest", latitude: 32.7668, longitude: -96.5992, metro: "Dallas-Fort Worth-Arlington" },
  { slug: "kansas-city-ks", city: "Kansas City", state: "Kansas", stateCode: "KS", population: 156607, tier: "medium", region: "Midwest", latitude: 39.1141, longitude: -94.6275, metro: "Kansas City" },
  { slug: "roseville-ca", city: "Roseville", state: "California", stateCode: "CA", population: 147773, tier: "medium", region: "West", latitude: 38.7521, longitude: -121.2880, metro: "Sacramento-Roseville-Folsom" },
  { slug: "bellevue-wa", city: "Bellevue", state: "Washington", stateCode: "WA", population: 151854, tier: "medium", region: "West", latitude: 47.6101, longitude: -122.2015, metro: "Seattle-Tacoma-Bellevue" },
  { slug: "surprise-az", city: "Surprise", state: "Arizona", stateCode: "AZ", population: 143148, tier: "medium", region: "Southwest", latitude: 33.6292, longitude: -112.3679, metro: "Phoenix-Mesa-Chandler" },
  { slug: "naperville-il", city: "Naperville", state: "Illinois", stateCode: "IL", population: 149540, tier: "medium", region: "Midwest", latitude: 41.7508, longitude: -88.1535, metro: "Chicago-Naperville-Elgin" },
  { slug: "thornton-co", city: "Thornton", state: "Colorado", stateCode: "CO", population: 141867, tier: "medium", region: "West", latitude: 39.8680, longitude: -104.9719, metro: "Denver-Aurora-Lakewood" },
  { slug: "rockford-il", city: "Rockford", state: "Illinois", stateCode: "IL", population: 148655, tier: "medium", region: "Midwest", latitude: 42.2711, longitude: -89.0940, metro: "Rockford" },
  { slug: "torrance-ca", city: "Torrance", state: "California", stateCode: "CA", population: 145014, tier: "medium", region: "West", latitude: 33.8358, longitude: -118.3406, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "kent-wa", city: "Kent", state: "Washington", stateCode: "WA", population: 136588, tier: "medium", region: "West", latitude: 47.3809, longitude: -122.2348, metro: "Seattle-Tacoma-Bellevue" },
  { slug: "macon-ga", city: "Macon", state: "Georgia", stateCode: "GA", population: 157346, tier: "medium", region: "Southeast", latitude: 32.8407, longitude: -83.6324, metro: "Macon-Bibb County" },
  { slug: "mcallen-tx", city: "McAllen", state: "Texas", stateCode: "TX", population: 142210, tier: "medium", region: "Southwest", latitude: 26.2034, longitude: -98.2300, metro: "McAllen-Edinburg-Mission" },
  { slug: "fullerton-ca", city: "Fullerton", state: "California", stateCode: "CA", population: 139640, tier: "medium", region: "West", latitude: 33.8703, longitude: -117.9242, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "lakeland-fl", city: "Lakeland", state: "Florida", stateCode: "FL", population: 115997, tier: "medium", region: "Southeast", latitude: 28.0395, longitude: -81.9498, metro: "Lakeland-Winter Haven" },
  { slug: "gainesville-fl", city: "Gainesville", state: "Florida", stateCode: "FL", population: 145840, tier: "medium", region: "Southeast", latitude: 29.6516, longitude: -82.3248, metro: "Gainesville" },
  { slug: "west-valley-city-ut", city: "West Valley City", state: "Utah", stateCode: "UT", population: 140230, tier: "medium", region: "West", latitude: 40.6916, longitude: -112.0011, metro: "Salt Lake City" },
  { slug: "pomona-ca-1", city: "West Covina", state: "California", stateCode: "CA", population: 106098, tier: "medium", region: "West", latitude: 34.0686, longitude: -117.9390, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "warren-mi", city: "Warren", state: "Michigan", stateCode: "MI", population: 139387, tier: "medium", region: "Midwest", latitude: 42.5145, longitude: -83.0147, metro: "Detroit-Warren-Dearborn" },
  { slug: "columbia-sc", city: "Columbia", state: "South Carolina", stateCode: "SC", population: 136632, tier: "medium", region: "Southeast", latitude: 34.0007, longitude: -81.0348, metro: "Columbia" },
  { slug: "sterling-heights-mi", city: "Sterling Heights", state: "Michigan", stateCode: "MI", population: 134346, tier: "medium", region: "Midwest", latitude: 42.5803, longitude: -83.0302, metro: "Detroit-Warren-Dearborn" },
  { slug: "coral-springs-fl", city: "Coral Springs", state: "Florida", stateCode: "FL", population: 134394, tier: "medium", region: "Southeast", latitude: 26.2712, longitude: -80.2706, metro: "Miami-Fort Lauderdale-Pompano Beach" },
  { slug: "carrollton-tx", city: "Carrollton", state: "Texas", stateCode: "TX", population: 133434, tier: "medium", region: "Southwest", latitude: 32.9537, longitude: -96.8903, metro: "Dallas-Fort Worth-Arlington" },
  { slug: "waco-tx", city: "Waco", state: "Texas", stateCode: "TX", population: 138486, tier: "medium", region: "Southwest", latitude: 31.5493, longitude: -97.1467, metro: "Waco" },
  { slug: "hartford-ct", city: "Hartford", state: "Connecticut", stateCode: "CT", population: 121054, tier: "medium", region: "Northeast", latitude: 41.7658, longitude: -72.6734, metro: "Hartford-East Hartford-Middletown" },
  { slug: "new-haven-ct", city: "New Haven", state: "Connecticut", stateCode: "CT", population: 134023, tier: "medium", region: "Northeast", latitude: 41.3083, longitude: -72.9279, metro: "New Haven-Milford" },
  { slug: "elizabeth-nj", city: "Elizabeth", state: "New Jersey", stateCode: "NJ", population: 137298, tier: "medium", region: "Northeast", latitude: 40.6639, longitude: -74.2107, metro: "New York-Newark-Jersey City" },
  { slug: "lewisville-tx", city: "Lewisville", state: "Texas", stateCode: "TX", population: 115322, tier: "medium", region: "Southwest", latitude: 33.0462, longitude: -96.9942, metro: "Dallas-Fort Worth-Arlington" },
  { slug: "topeka-ks", city: "Topeka", state: "Kansas", stateCode: "KS", population: 126587, tier: "medium", region: "Midwest", latitude: 39.0473, longitude: -95.6752, metro: "Topeka" },
  { slug: "stamford-ct", city: "Stamford", state: "Connecticut", stateCode: "CT", population: 135470, tier: "medium", region: "Northeast", latitude: 41.0534, longitude: -73.5387, metro: "Bridgeport-Stamford-Norwalk" },
  { slug: "concord-ca", city: "Concord", state: "California", stateCode: "CA", population: 129295, tier: "medium", region: "West", latitude: 37.9780, longitude: -122.0311, metro: "San Francisco-Oakland-Berkeley" },
  { slug: "simi-valley-ca", city: "Simi Valley", state: "California", stateCode: "CA", population: 126871, tier: "medium", region: "West", latitude: 34.2694, longitude: -118.7815, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "thousand-oaks-ca", city: "Thousand Oaks", state: "California", stateCode: "CA", population: 126966, tier: "medium", region: "West", latitude: 34.1706, longitude: -118.8376, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "lafayette-la", city: "Lafayette", state: "Louisiana", stateCode: "LA", population: 126848, tier: "medium", region: "Southeast", latitude: 30.2241, longitude: -92.0198, metro: "Lafayette" },
  { slug: "norman-ok", city: "Norman", state: "Oklahoma", stateCode: "OK", population: 128026, tier: "medium", region: "Southwest", latitude: 35.2226, longitude: -97.4395, metro: "Oklahoma City" },
  { slug: "athens-ga", city: "Athens", state: "Georgia", stateCode: "GA", population: 127315, tier: "medium", region: "Southeast", latitude: 33.9519, longitude: -83.3576, metro: "Athens-Clarke County" },
  { slug: "clearwater-fl", city: "Clearwater", state: "Florida", stateCode: "FL", population: 117292, tier: "medium", region: "Southeast", latitude: 27.9659, longitude: -82.8001, metro: "Tampa-St. Petersburg-Clearwater" },
  { slug: "victorville-ca", city: "Victorville", state: "California", stateCode: "CA", population: 134810, tier: "medium", region: "West", latitude: 34.5362, longitude: -117.2928, metro: "Riverside-San Bernardino-Ontario" },
  { slug: "abilene-tx", city: "Abilene", state: "Texas", stateCode: "TX", population: 123676, tier: "medium", region: "Southwest", latitude: 32.4487, longitude: -99.7331, metro: "Abilene" },
  { slug: "vallejo-ca", city: "Vallejo", state: "California", stateCode: "CA", population: 121253, tier: "medium", region: "West", latitude: 38.1041, longitude: -122.2566, metro: "Vallejo" },
  { slug: "allentown-pa", city: "Allentown", state: "Pennsylvania", stateCode: "PA", population: 126092, tier: "medium", region: "Northeast", latitude: 40.6084, longitude: -75.4902, metro: "Allentown-Bethlehem-Easton" },
  { slug: "evansville-in", city: "Evansville", state: "Indiana", stateCode: "IN", population: 117298, tier: "medium", region: "Midwest", latitude: 37.9716, longitude: -87.5711, metro: "Evansville" },
  { slug: "provo-ut", city: "Provo", state: "Utah", stateCode: "UT", population: 115162, tier: "medium", region: "West", latitude: 40.2338, longitude: -111.6585, metro: "Provo-Orem" },
  { slug: "ann-arbor-mi", city: "Ann Arbor", state: "Michigan", stateCode: "MI", population: 123851, tier: "medium", region: "Midwest", latitude: 42.2808, longitude: -83.7430, metro: "Ann Arbor" },
  { slug: "lansing-mi", city: "Lansing", state: "Michigan", stateCode: "MI", population: 112644, tier: "medium", region: "Midwest", latitude: 42.7325, longitude: -84.5555, metro: "Lansing-East Lansing" },
  { slug: "denton-tx", city: "Denton", state: "Texas", stateCode: "TX", population: 139869, tier: "medium", region: "Southwest", latitude: 33.2148, longitude: -97.1331, metro: "Dallas-Fort Worth-Arlington" },
  { slug: "berkeley-ca", city: "Berkeley", state: "California", stateCode: "CA", population: 124321, tier: "medium", region: "West", latitude: 37.8715, longitude: -122.2730, metro: "San Francisco-Oakland-Berkeley" },
  { slug: "fargo-nd", city: "Fargo", state: "North Dakota", stateCode: "ND", population: 125990, tier: "medium", region: "Midwest", latitude: 46.8772, longitude: -96.7898, metro: "Fargo" },
  { slug: "round-rock-tx", city: "Round Rock", state: "Texas", stateCode: "TX", population: 119468, tier: "medium", region: "Southwest", latitude: 30.5083, longitude: -97.6789, metro: "Austin-Round Rock-Georgetown" },
  { slug: "independence-mo", city: "Independence", state: "Missouri", stateCode: "MO", population: 123011, tier: "medium", region: "Midwest", latitude: 39.0911, longitude: -94.4155, metro: "Kansas City" },
  { slug: "downey-ca", city: "Downey", state: "California", stateCode: "CA", population: 111772, tier: "medium", region: "West", latitude: 33.9401, longitude: -118.1332, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "costa-mesa-ca", city: "Costa Mesa", state: "California", stateCode: "CA", population: 112174, tier: "medium", region: "West", latitude: 33.6411, longitude: -117.9187, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "inglewood-ca", city: "Inglewood", state: "California", stateCode: "CA", population: 107762, tier: "medium", region: "West", latitude: 33.9617, longitude: -118.3531, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "peoria-il", city: "Peoria", state: "Illinois", stateCode: "IL", population: 113150, tier: "medium", region: "Midwest", latitude: 40.6936, longitude: -89.5890, metro: "Peoria" },
  { slug: "arvada-co", city: "Arvada", state: "Colorado", stateCode: "CO", population: 124402, tier: "medium", region: "West", latitude: 39.8028, longitude: -105.0875, metro: "Denver-Aurora-Lakewood" },
  { slug: "elgin-il", city: "Elgin", state: "Illinois", stateCode: "IL", population: 114797, tier: "medium", region: "Midwest", latitude: 42.0354, longitude: -88.2826, metro: "Chicago-Naperville-Elgin" },
  { slug: "wilmington-nc", city: "Wilmington", state: "North Carolina", stateCode: "NC", population: 115451, tier: "medium", region: "Southeast", latitude: 34.2257, longitude: -77.9447, metro: "Wilmington" },
  { slug: "west-jordan-ut", city: "West Jordan", state: "Utah", stateCode: "UT", population: 116961, tier: "medium", region: "West", latitude: 40.6097, longitude: -111.9391, metro: "Salt Lake City" },
  { slug: "dayton-oh", city: "Dayton", state: "Ohio", stateCode: "OH", population: 137644, tier: "medium", region: "Midwest", latitude: 39.7589, longitude: -84.1916, metro: "Dayton" },
  { slug: "charleston-sc", city: "Charleston", state: "South Carolina", stateCode: "SC", population: 150227, tier: "medium", region: "Southeast", latitude: 32.7765, longitude: -79.9311, metro: "Charleston-North Charleston" },
  { slug: "pompano-beach-fl", city: "Pompano Beach", state: "Florida", stateCode: "FL", population: 112046, tier: "medium", region: "Southeast", latitude: 26.2379, longitude: -80.1248, metro: "Miami-Fort Lauderdale-Pompano Beach" },
  { slug: "west-palm-beach-fl", city: "West Palm Beach", state: "Florida", stateCode: "FL", population: 117415, tier: "medium", region: "Southeast", latitude: 26.7153, longitude: -80.0534, metro: "Miami-Fort Lauderdale-Pompano Beach" },
  { slug: "lowell-ma", city: "Lowell", state: "Massachusetts", stateCode: "MA", population: 115554, tier: "medium", region: "Northeast", latitude: 42.6334, longitude: -71.3162, metro: "Boston-Cambridge-Newton" },
  { slug: "waterbury-ct", city: "Waterbury", state: "Connecticut", stateCode: "CT", population: 114403, tier: "medium", region: "Northeast", latitude: 41.5582, longitude: -73.0515, metro: "Waterbury" },
  { slug: "billings-mt", city: "Billings", state: "Montana", stateCode: "MT", population: 117116, tier: "medium", region: "West", latitude: 45.7833, longitude: -108.5007, metro: "Billings" },
  { slug: "pueblo-co", city: "Pueblo", state: "Colorado", stateCode: "CO", population: 111876, tier: "medium", region: "West", latitude: 38.2544, longitude: -104.6091, metro: "Pueblo" },
  { slug: "rochester-mn", city: "Rochester", state: "Minnesota", stateCode: "MN", population: 121395, tier: "medium", region: "Midwest", latitude: 44.0121, longitude: -92.4802, metro: "Rochester" },
  { slug: "gresham-or", city: "Gresham", state: "Oregon", stateCode: "OR", population: 114247, tier: "medium", region: "West", latitude: 45.4979, longitude: -122.4328, metro: "Portland-Vancouver-Hillsboro" },
  { slug: "high-point-nc", city: "High Point", state: "North Carolina", stateCode: "NC", population: 114059, tier: "medium", region: "Southeast", latitude: 35.9557, longitude: -80.0053, metro: "Greensboro-High Point" },
  { slug: "cambridge-ma", city: "Cambridge", state: "Massachusetts", stateCode: "MA", population: 118403, tier: "medium", region: "Northeast", latitude: 42.3736, longitude: -71.1097, metro: "Boston-Cambridge-Newton" },
  { slug: "antioch-ca", city: "Antioch", state: "California", stateCode: "CA", population: 115291, tier: "medium", region: "West", latitude: 38.0049, longitude: -121.8058, metro: "San Francisco-Oakland-Berkeley" },
  { slug: "lewisville-tx-1", city: "Sugar Land", state: "Texas", stateCode: "TX", population: 111026, tier: "medium", region: "Southwest", latitude: 29.6196, longitude: -95.6349, metro: "Houston-The Woodlands-Sugar Land" },
  { slug: "pearland-tx", city: "Pearland", state: "Texas", stateCode: "TX", population: 125828, tier: "medium", region: "Southwest", latitude: 29.5636, longitude: -95.2860, metro: "Houston-The Woodlands-Sugar Land" },
];

// Tier 4: Smaller Cities (Pop 75K-100K) - 100 cities
const smallCities: USCity[] = [
  { slug: "santa-maria-ca", city: "Santa Maria", state: "California", stateCode: "CA", population: 108470, tier: "small", region: "West", latitude: 34.9530, longitude: -120.4357, metro: "Santa Maria-Santa Barbara" },
  { slug: "college-station-tx", city: "College Station", state: "Texas", stateCode: "TX", population: 115802, tier: "small", region: "Southwest", latitude: 30.6280, longitude: -96.3344, metro: "College Station-Bryan" },
  { slug: "meridian-id", city: "Meridian", state: "Idaho", stateCode: "ID", population: 117635, tier: "small", region: "West", latitude: 43.6121, longitude: -116.3915, metro: "Boise City" },
  { slug: "green-bay-wi", city: "Green Bay", state: "Wisconsin", stateCode: "WI", population: 107395, tier: "small", region: "Midwest", latitude: 44.5133, longitude: -88.0133, metro: "Green Bay" },
  { slug: "new-bedford-ma", city: "New Bedford", state: "Massachusetts", stateCode: "MA", population: 101079, tier: "small", region: "Northeast", latitude: 41.6362, longitude: -70.9342, metro: "New Bedford" },
  { slug: "sandy-springs-ga", city: "Sandy Springs", state: "Georgia", stateCode: "GA", population: 108080, tier: "small", region: "Southeast", latitude: 33.9304, longitude: -84.3733, metro: "Atlanta-Sandy Springs-Alpharetta" },
  { slug: "west-covina-ca", city: "West Covina", state: "California", stateCode: "CA", population: 106098, tier: "small", region: "West", latitude: 34.0686, longitude: -117.9390, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "el-cajon-ca", city: "El Cajon", state: "California", stateCode: "CA", population: 106215, tier: "small", region: "West", latitude: 32.7948, longitude: -116.9625, metro: "San Diego-Carlsbad" },
  { slug: "davie-fl", city: "Davie", state: "Florida", stateCode: "FL", population: 105691, tier: "small", region: "Southeast", latitude: 26.0765, longitude: -80.2521, metro: "Miami-Fort Lauderdale-Pompano Beach" },
  { slug: "centennial-co", city: "Centennial", state: "Colorado", stateCode: "CO", population: 108418, tier: "small", region: "West", latitude: 39.5807, longitude: -104.8772, metro: "Denver-Aurora-Lakewood" },
  { slug: "jurupa-valley-ca", city: "Jurupa Valley", state: "California", stateCode: "CA", population: 113569, tier: "small", region: "West", latitude: 33.9972, longitude: -117.4854, metro: "Riverside-San Bernardino-Ontario" },
  { slug: "el-monte-ca", city: "El Monte", state: "California", stateCode: "CA", population: 113475, tier: "small", region: "West", latitude: 34.0686, longitude: -118.0276, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "allen-tx", city: "Allen", state: "Texas", stateCode: "TX", population: 105623, tier: "small", region: "Southwest", latitude: 33.1032, longitude: -96.6706, metro: "Dallas-Fort Worth-Arlington" },
  { slug: "sparks-nv", city: "Sparks", state: "Nevada", stateCode: "NV", population: 108445, tier: "small", region: "West", latitude: 39.5349, longitude: -119.7527, metro: "Reno" },
  { slug: "rialto-ca", city: "Rialto", state: "California", stateCode: "CA", population: 104026, tier: "small", region: "West", latitude: 34.1064, longitude: -117.3703, metro: "Riverside-San Bernardino-Ontario" },
  { slug: "las-cruces-nm", city: "Las Cruces", state: "New Mexico", stateCode: "NM", population: 111385, tier: "small", region: "Southwest", latitude: 32.3199, longitude: -106.7637, metro: "Las Cruces" },
  { slug: "murrieta-ca", city: "Murrieta", state: "California", stateCode: "CA", population: 113299, tier: "small", region: "West", latitude: 33.5539, longitude: -117.2139, metro: "Riverside-San Bernardino-Ontario" },
  { slug: "tuscaloosa-al", city: "Tuscaloosa", state: "Alabama", stateCode: "AL", population: 100618, tier: "small", region: "Southeast", latitude: 33.2098, longitude: -87.5692, metro: "Tuscaloosa" },
  { slug: "vista-ca", city: "Vista", state: "California", stateCode: "CA", population: 101659, tier: "small", region: "West", latitude: 33.2000, longitude: -117.2425, metro: "San Diego-Carlsbad" },
  { slug: "stamford-ct-1", city: "Norwalk", state: "Connecticut", stateCode: "CT", population: 91184, tier: "small", region: "Northeast", latitude: 41.1176, longitude: -73.4078, metro: "Bridgeport-Stamford-Norwalk" },
  { slug: "lee-summit-mo", city: "Lee's Summit", state: "Missouri", stateCode: "MO", population: 101108, tier: "small", region: "Midwest", latitude: 38.9108, longitude: -94.3822, metro: "Kansas City" },
  { slug: "renton-wa", city: "Renton", state: "Washington", stateCode: "WA", population: 106785, tier: "small", region: "West", latitude: 47.4829, longitude: -122.2171, metro: "Seattle-Tacoma-Bellevue" },
  { slug: "edison-nj", city: "Edison", state: "New Jersey", stateCode: "NJ", population: 107588, tier: "small", region: "Northeast", latitude: 40.5187, longitude: -74.4121, metro: "New York-Newark-Jersey City" },
  { slug: "rio-rancho-nm", city: "Rio Rancho", state: "New Mexico", stateCode: "NM", population: 104046, tier: "small", region: "Southwest", latitude: 35.2328, longitude: -106.6630, metro: "Albuquerque" },
  { slug: "nampa-id", city: "Nampa", state: "Idaho", stateCode: "ID", population: 100200, tier: "small", region: "West", latitude: 43.5407, longitude: -116.5635, metro: "Boise City" },
  { slug: "san-leandro-ca", city: "San Leandro", state: "California", stateCode: "CA", population: 91479, tier: "small", region: "West", latitude: 37.7249, longitude: -122.1561, metro: "San Francisco-Oakland-Berkeley" },
  { slug: "tyler-tx", city: "Tyler", state: "Texas", stateCode: "TX", population: 105995, tier: "small", region: "Southwest", latitude: 32.3513, longitude: -95.3011, metro: "Tyler" },
  { slug: "woodbridge-nj", city: "Woodbridge", state: "New Jersey", stateCode: "NJ", population: 105135, tier: "small", region: "Northeast", latitude: 40.5576, longitude: -74.2846, metro: "New York-Newark-Jersey City" },
  { slug: "broken-arrow-ok", city: "Broken Arrow", state: "Oklahoma", stateCode: "OK", population: 113540, tier: "small", region: "Southwest", latitude: 36.0526, longitude: -95.7908, metro: "Tulsa" },
  { slug: "daly-city-ca", city: "Daly City", state: "California", stateCode: "CA", population: 104901, tier: "small", region: "West", latitude: 37.6879, longitude: -122.4702, metro: "San Francisco-Oakland-Berkeley" },
  { slug: "league-city-tx", city: "League City", state: "Texas", stateCode: "TX", population: 115595, tier: "small", region: "Southwest", latitude: 29.5075, longitude: -95.0949, metro: "Houston-The Woodlands-Sugar Land" },
  { slug: "south-bend-in", city: "South Bend", state: "Indiana", stateCode: "IN", population: 103453, tier: "small", region: "Midwest", latitude: 41.6764, longitude: -86.2520, metro: "South Bend-Mishawaka" },
  { slug: "quincy-ma", city: "Quincy", state: "Massachusetts", stateCode: "MA", population: 101636, tier: "small", region: "Northeast", latitude: 42.2529, longitude: -71.0023, metro: "Boston-Cambridge-Newton" },
  { slug: "menifee-ca", city: "Menifee", state: "California", stateCode: "CA", population: 102527, tier: "small", region: "West", latitude: 33.6971, longitude: -117.1468, metro: "Riverside-San Bernardino-Ontario" },
  { slug: "spokane-valley-wa", city: "Spokane Valley", state: "Washington", stateCode: "WA", population: 102976, tier: "small", region: "West", latitude: 47.6732, longitude: -117.2394, metro: "Spokane-Spokane Valley" },
  { slug: "santa-clara-ca", city: "Santa Clara", state: "California", stateCode: "CA", population: 127647, tier: "small", region: "West", latitude: 37.3541, longitude: -121.9552, metro: "San Jose-Sunnyvale-Santa Clara" },
  { slug: "edinburg-tx", city: "Edinburg", state: "Texas", stateCode: "TX", population: 101170, tier: "small", region: "Southwest", latitude: 26.3017, longitude: -98.1633, metro: "McAllen-Edinburg-Mission" },
  { slug: "brandon-fl", city: "Brandon", state: "Florida", stateCode: "FL", population: 115911, tier: "small", region: "Southeast", latitude: 27.9378, longitude: -82.2859, metro: "Tampa-St. Petersburg-Clearwater" },
  { slug: "temecula-ca", city: "Temecula", state: "California", stateCode: "CA", population: 110003, tier: "small", region: "West", latitude: 33.4936, longitude: -117.1484, metro: "Riverside-San Bernardino-Ontario" },
  { slug: "palm-bay-fl", city: "Palm Bay", state: "Florida", stateCode: "FL", population: 119760, tier: "small", region: "Southeast", latitude: 28.0345, longitude: -80.5887, metro: "Palm Bay-Melbourne-Titusville" },
  { slug: "davenport-ia", city: "Davenport", state: "Iowa", stateCode: "IA", population: 101724, tier: "small", region: "Midwest", latitude: 41.5236, longitude: -90.5776, metro: "Davenport-Moline-Rock Island" },
  { slug: "sunrise-fl", city: "Sunrise", state: "Florida", stateCode: "FL", population: 97335, tier: "small", region: "Southeast", latitude: 26.1336, longitude: -80.1131, metro: "Miami-Fort Lauderdale-Pompano Beach" },
  { slug: "plantation-fl", city: "Plantation", state: "Florida", stateCode: "FL", population: 94580, tier: "small", region: "Southeast", latitude: 26.1276, longitude: -80.2331, metro: "Miami-Fort Lauderdale-Pompano Beach" },
  { slug: "deltona-fl", city: "Deltona", state: "Florida", stateCode: "FL", population: 96238, tier: "small", region: "Southeast", latitude: 28.9005, longitude: -81.2637, metro: "Deltona-Daytona Beach-Ormond Beach" },
  { slug: "boca-raton-fl", city: "Boca Raton", state: "Florida", stateCode: "FL", population: 99805, tier: "small", region: "Southeast", latitude: 26.3683, longitude: -80.1289, metro: "Miami-Fort Lauderdale-Pompano Beach" },
  { slug: "boulder-co", city: "Boulder", state: "Colorado", stateCode: "CO", population: 105485, tier: "small", region: "West", latitude: 40.0150, longitude: -105.2705, metro: "Boulder" },
  { slug: "wichita-falls-tx", city: "Wichita Falls", state: "Texas", stateCode: "TX", population: 102316, tier: "small", region: "Southwest", latitude: 33.9137, longitude: -98.4934, metro: "Wichita Falls" },
  { slug: "palm-coast-fl", city: "Palm Coast", state: "Florida", stateCode: "FL", population: 98286, tier: "small", region: "Southeast", latitude: 29.5389, longitude: -81.2456, metro: "Palm Coast" },
  { slug: "ventura-ca", city: "Ventura", state: "California", stateCode: "CA", population: 109106, tier: "small", region: "West", latitude: 34.2746, longitude: -119.2290, metro: "Ventura" },
  { slug: "redding-ca", city: "Redding", state: "California", stateCode: "CA", population: 93266, tier: "small", region: "West", latitude: 40.5865, longitude: -122.3917, metro: "Redding" },
  { slug: "bend-or", city: "Bend", state: "Oregon", stateCode: "OR", population: 102059, tier: "small", region: "West", latitude: 44.0582, longitude: -121.3153, metro: "Bend" },
  { slug: "springfield-il", city: "Springfield", state: "Illinois", stateCode: "IL", population: 114230, tier: "small", region: "Midwest", latitude: 39.7817, longitude: -89.6501, metro: "Springfield" },
  { slug: "chico-ca", city: "Chico", state: "California", stateCode: "CA", population: 101475, tier: "small", region: "West", latitude: 39.7285, longitude: -121.8375, metro: "Chico" },
  { slug: "hesperia-ca", city: "Hesperia", state: "California", stateCode: "CA", population: 99818, tier: "small", region: "West", latitude: 34.4264, longitude: -117.3009, metro: "Riverside-San Bernardino-Ontario" },
  { slug: "carmel-in", city: "Carmel", state: "Indiana", stateCode: "IN", population: 101068, tier: "small", region: "Midwest", latitude: 39.9784, longitude: -86.1180, metro: "Indianapolis-Carmel-Anderson" },
  { slug: "vacaville-ca", city: "Vacaville", state: "California", stateCode: "CA", population: 103078, tier: "small", region: "West", latitude: 38.3566, longitude: -121.9877, metro: "Vallejo" },
  { slug: "santa-fe-nm", city: "Santa Fe", state: "New Mexico", stateCode: "NM", population: 89177, tier: "small", region: "Southwest", latitude: 35.6870, longitude: -105.9378, metro: "Santa Fe" },
  { slug: "conroe-tx", city: "Conroe", state: "Texas", stateCode: "TX", population: 97872, tier: "small", region: "Southwest", latitude: 30.3119, longitude: -95.4560, metro: "Houston-The Woodlands-Sugar Land" },
  { slug: "hemet-ca", city: "Hemet", state: "California", stateCode: "CA", population: 90403, tier: "small", region: "West", latitude: 33.7476, longitude: -116.9719, metro: "Riverside-San Bernardino-Ontario" },
  { slug: "lakewood-nj", city: "Lakewood", state: "New Jersey", stateCode: "NJ", population: 135158, tier: "small", region: "Northeast", latitude: 40.0979, longitude: -74.2177, metro: "New York-Newark-Jersey City" },
  { slug: "odessa-tx", city: "Odessa", state: "Texas", stateCode: "TX", population: 123334, tier: "small", region: "Southwest", latitude: 31.8457, longitude: -102.3676, metro: "Odessa" },
  { slug: "midland-tx", city: "Midland", state: "Texas", stateCode: "TX", population: 132950, tier: "small", region: "Southwest", latitude: 31.9973, longitude: -102.0779, metro: "Midland" },
  { slug: "mission-viejo-ca", city: "Mission Viejo", state: "California", stateCode: "CA", population: 95290, tier: "small", region: "West", latitude: 33.6000, longitude: -117.6720, metro: "Los Angeles-Long Beach-Anaheim" },
  { slug: "fishers-in", city: "Fishers", state: "Indiana", stateCode: "IN", population: 98977, tier: "small", region: "Midwest", latitude: 39.9568, longitude: -86.0133, metro: "Indianapolis-Carmel-Anderson" },
  { slug: "o-fallon-mo", city: "O'Fallon", state: "Missouri", stateCode: "MO", population: 91316, tier: "small", region: "Midwest", latitude: 38.8106, longitude: -90.6998, metro: "St. Louis" },
  { slug: "racine-wi", city: "Racine", state: "Wisconsin", stateCode: "WI", population: 77816, tier: "small", region: "Midwest", latitude: 42.7261, longitude: -87.7829, metro: "Racine" },
  { slug: "kenosha-wi", city: "Kenosha", state: "Wisconsin", stateCode: "WI", population: 99877, tier: "small", region: "Midwest", latitude: 42.5847, longitude: -87.8212, metro: "Chicago-Naperville-Elgin" },
  { slug: "portsmouth-va", city: "Portsmouth", state: "Virginia", stateCode: "VA", population: 97915, tier: "small", region: "Southeast", latitude: 36.8354, longitude: -76.2983, metro: "Virginia Beach-Norfolk-Newport News" },
  { slug: "santa-barbara-ca", city: "Santa Barbara", state: "California", stateCode: "CA", population: 88665, tier: "small", region: "West", latitude: 34.4208, longitude: -119.6982, metro: "Santa Maria-Santa Barbara" },
  { slug: "la-mesa-ca", city: "La Mesa", state: "California", stateCode: "CA", population: 61203, tier: "small", region: "West", latitude: 32.7678, longitude: -117.0231, metro: "San Diego-Carlsbad" },
  { slug: "pensacola-fl", city: "Pensacola", state: "Florida", stateCode: "FL", population: 54312, tier: "small", region: "Southeast", latitude: 30.4213, longitude: -87.2169, metro: "Pensacola-Ferry Pass-Brent" },
  { slug: "duluth-mn", city: "Duluth", state: "Minnesota", stateCode: "MN", population: 90880, tier: "small", region: "Midwest", latitude: 46.7867, longitude: -92.1005, metro: "Duluth" },
  { slug: "bloomington-mn", city: "Bloomington", state: "Minnesota", stateCode: "MN", population: 89987, tier: "small", region: "Midwest", latitude: 44.8408, longitude: -93.2983, metro: "Minneapolis-St. Paul-Bloomington" },
  { slug: "apple-valley-ca", city: "Apple Valley", state: "California", stateCode: "CA", population: 75791, tier: "small", region: "West", latitude: 34.5008, longitude: -117.1859, metro: "Riverside-San Bernardino-Ontario" },
  { slug: "eagan-mn", city: "Eagan", state: "Minnesota", stateCode: "MN", population: 70307, tier: "small", region: "Midwest", latitude: 44.8041, longitude: -93.1669, metro: "Minneapolis-St. Paul-Bloomington" },
  { slug: "rapid-city-sd", city: "Rapid City", state: "South Dakota", stateCode: "SD", population: 74703, tier: "small", region: "Midwest", latitude: 44.0805, longitude: -103.2310, metro: "Rapid City" },
  { slug: "san-marcos-ca", city: "San Marcos", state: "California", stateCode: "CA", population: 97479, tier: "small", region: "West", latitude: 33.1434, longitude: -117.1661, metro: "San Diego-Carlsbad" },
  { slug: "livonia-mi", city: "Livonia", state: "Michigan", stateCode: "MI", population: 94542, tier: "small", region: "Midwest", latitude: 42.3684, longitude: -83.3527, metro: "Detroit-Warren-Dearborn" },
  { slug: "parma-oh", city: "Parma", state: "Ohio", stateCode: "OH", population: 81601, tier: "small", region: "Midwest", latitude: 41.4048, longitude: -81.7229, metro: "Cleveland-Elyria" },
  { slug: "troy-mi", city: "Troy", state: "Michigan", stateCode: "MI", population: 87294, tier: "small", region: "Midwest", latitude: 42.6064, longitude: -83.1498, metro: "Detroit-Warren-Dearborn" },
  { slug: "cedar-rapids-ia", city: "Cedar Rapids", state: "Iowa", stateCode: "IA", population: 137710, tier: "small", region: "Midwest", latitude: 41.9779, longitude: -91.6656, metro: "Cedar Rapids" },
  { slug: "dearborn-mi", city: "Dearborn", state: "Michigan", stateCode: "MI", population: 109976, tier: "small", region: "Midwest", latitude: 42.3223, longitude: -83.1763, metro: "Detroit-Warren-Dearborn" },
  { slug: "delray-beach-fl", city: "Delray Beach", state: "Florida", stateCode: "FL", population: 69451, tier: "small", region: "Southeast", latitude: 26.4615, longitude: -80.0728, metro: "Miami-Fort Lauderdale-Pompano Beach" },
  { slug: "boynton-beach-fl", city: "Boynton Beach", state: "Florida", stateCode: "FL", population: 80380, tier: "small", region: "Southeast", latitude: 26.5254, longitude: -80.0662, metro: "Miami-Fort Lauderdale-Pompano Beach" },
  { slug: "chino-ca", city: "Chino", state: "California", stateCode: "CA", population: 91403, tier: "small", region: "West", latitude: 34.0122, longitude: -117.6889, metro: "Riverside-San Bernardino-Ontario" },
  { slug: "upland-ca", city: "Upland", state: "California", stateCode: "CA", population: 79040, tier: "small", region: "West", latitude: 34.0975, longitude: -117.6484, metro: "Riverside-San Bernardino-Ontario" },
  { slug: "sanford-fl", city: "Sanford", state: "Florida", stateCode: "FL", population: 63285, tier: "small", region: "Southeast", latitude: 28.8003, longitude: -81.2731, metro: "Orlando-Kissimmee-Sanford" },
  { slug: "federal-way-wa", city: "Federal Way", state: "Washington", stateCode: "WA", population: 101030, tier: "small", region: "West", latitude: 47.3223, longitude: -122.3126, metro: "Seattle-Tacoma-Bellevue" },
  { slug: "bellingham-wa", city: "Bellingham", state: "Washington", stateCode: "WA", population: 91482, tier: "small", region: "West", latitude: 48.7519, longitude: -122.4787, metro: "Bellingham" },
  { slug: "redwood-city-ca", city: "Redwood City", state: "California", stateCode: "CA", population: 84292, tier: "small", region: "West", latitude: 37.4852, longitude: -122.2364, metro: "San Francisco-Oakland-Berkeley" },
  { slug: "westminster-co", city: "Westminster", state: "Colorado", stateCode: "CO", population: 116317, tier: "small", region: "West", latitude: 39.8367, longitude: -105.0372, metro: "Denver-Aurora-Lakewood" },
  { slug: "mission-tx", city: "Mission", state: "Texas", stateCode: "TX", population: 84827, tier: "small", region: "Southwest", latitude: 26.2159, longitude: -98.3253, metro: "McAllen-Edinburg-Mission" },
  { slug: "longmont-co", city: "Longmont", state: "Colorado", stateCode: "CO", population: 98629, tier: "small", region: "West", latitude: 40.1672, longitude: -105.1019, metro: "Boulder" },
  { slug: "goodyear-az", city: "Goodyear", state: "Arizona", stateCode: "AZ", population: 95294, tier: "small", region: "Southwest", latitude: 33.4353, longitude: -112.3581, metro: "Phoenix-Mesa-Chandler" },
  { slug: "buckeye-az", city: "Buckeye", state: "Arizona", stateCode: "AZ", population: 91502, tier: "small", region: "Southwest", latitude: 33.3703, longitude: -112.5838, metro: "Phoenix-Mesa-Chandler" },
  { slug: "san-ramon-ca", city: "San Ramon", state: "California", stateCode: "CA", population: 83280, tier: "small", region: "West", latitude: 37.7799, longitude: -121.9780, metro: "San Francisco-Oakland-Berkeley" },
  { slug: "homestead-fl", city: "Homestead", state: "Florida", stateCode: "FL", population: 80110, tier: "small", region: "Southeast", latitude: 25.4687, longitude: -80.4776, metro: "Miami-Fort Lauderdale-Pompano Beach" },
  { slug: "largo-fl", city: "Largo", state: "Florida", stateCode: "FL", population: 84959, tier: "small", region: "Southeast", latitude: 27.9095, longitude: -82.7873, metro: "Tampa-St. Petersburg-Clearwater" },
  { slug: "gary-in", city: "Gary", state: "Indiana", stateCode: "IN", population: 69093, tier: "small", region: "Midwest", latitude: 41.5934, longitude: -87.3465, metro: "Chicago-Naperville-Elgin" },
];

// Export all cities combined
export const usTop350Cities: USCity[] = [
  ...majorCities,
  ...largeCities,
  ...mediumCities,
  ...smallCities,
];

// Export by tier
export const usCitiesByTier = {
  major: majorCities,
  large: largeCities,
  medium: mediumCities,
  small: smallCities,
};

// Helper functions
export function getUSCityBySlug(slug: string): USCity | undefined {
  return usTop350Cities.find(c => c.slug === slug);
}

export function getUSCitiesByState(stateCode: string): USCity[] {
  return usTop350Cities.filter(c => c.stateCode === stateCode);
}

export function getUSCitiesByRegion(region: USCity['region']): USCity[] {
  return usTop350Cities.filter(c => c.region === region);
}

export function getUSCitiesByTier(tier: USCity['tier']): USCity[] {
  return usTop350Cities.filter(c => c.tier === tier);
}

export function getAllUSCitySlugs(): string[] {
  return usTop350Cities.map(c => c.slug);
}

export function getNearbyUSCities(slug: string, limit: number = 5): USCity[] {
  const city = getUSCityBySlug(slug);
  if (!city) return [];
  
  // Find cities in the same state or region
  return usTop350Cities
    .filter(c => c.slug !== slug && (c.stateCode === city.stateCode || c.region === city.region))
    .slice(0, limit);
}

// Export totals
export const US_CITIES_TOTAL = usTop350Cities.length;
export const US_CITIES_BY_TIER_COUNT = {
  major: majorCities.length,
  large: largeCities.length,
  medium: mediumCities.length,
  small: smallCities.length,
};
